### ISSUE TITLE
Time for 0.4?

### ISSUE THREAD

**Issue by thedrow** [root-project/cling#134]
Since the last release, there was quite a bit of progress. Is it time for 0.4?

**Comment by Axel-Naumann** [comment]
We agree :-) Vassil offered to do it. It'll happen fairly soon, before the llvm/clang upgrade that he's currently  working on.

**Comment by Axel-Naumann** [comment]
v0.4 is released: https://github.com/root-project/cling/blob/v0.4/docs/ReleaseNotes.md

Thanks for nudging us to do it :-)
