### ISSUE TITLE
[Q] Access to the caller frame

### ISSUE THREAD

**Issue by Mic92** [root-project/cling#172]
I saw the [cling-demo](https://github.com/root-project/cling/blob/master/tools/demo/cling-demo.cpp) and wondered if there is something, which prevents me from accessing local variables the the stack frame, where the interpreter was called. 

My use case is the following:

I have a static compiled program, where I want to explore my program state in function `foo()`.
There for I would insert ahead of execution a function called `invokeCling()` into my program:

```
void foo(int a) {
  int b;
  invokeCling();
}
```

`invokeCling()` would then figure out its caller and use debug symbols or consult an debugger to get more information about the call frame (to get the address of local variables and their types). These information could be then used to passed to cling to make accessible from within the repl.

Do you think this is possible? Can I use [Interpreter::declare](https://github.com/root-project/cling/blob/master/tools/demo/cling-demo.cpp#L28) to get access to variables, which are not global symbols?

Similar approaches in other programming languages:
- [pry in ruby](http://pryrepl.org/)
- [python's pdb](https://docs.python.org/2/library/pdb.html#pdb.set_trace)
- [evaluate expressions in java](https://www.jetbrains.com/help/idea/evaluating-expressions.html)

**Comment by Axel-Naumann** [comment]
Hi Jörg,

Yes that should be possible, but it will require you to
- determine the current frame (foo)
- determine the function symbol it corresponds to
- grab the DWARF info for that function
- wrap all of that (names, types, stack locations) and provide it to cling.

lldb does something fairly similar. It shows that it's possible. But it also shows that it's non-trivial.

**Comment by Mic92** [comment]
Ideally I could reuse lldb here: http://lldb.llvm.org/architecture/#interpreter

**Comment by Mic92** [comment]
I will follow that approach instead: https://github.com/d4l3k/go-pry

**Comment by Axel-Naumann** [comment]
Thanks, @Mic92 - I'd be interested to hear what comes out of this: if you have some publicly visible code that implements this then please let us know!

**Comment by Mic92** [comment]
Let's see If I can convince people to join the hackathon.

**Comment by Mic92** [comment]
This is our hackathon prototyp: https://github.com/inspector-repl/inspector
The functionality works well, but it needs some more love to work in all environments well and we need to test more C++ code as we basically only tested our demo.

**Comment by Mic92** [comment]
Are there any plans to upstream the clang/llvm patches. I want to simplify packaging long term to integrate `cling` into the major linux distribution.
