### ISSUE TITLE
Unable to include header file written in C++14

### ISSUE THREAD

**Issue by shyam-jagannathan** [root-project/cling#185]
I am running on Ubuntu 14.04 LTS, 64bit

![image](https://user-images.githubusercontent.com/25835566/31499368-3062b448-af82-11e7-9bf5-4d2737e31240.png)

**Comment by shyam-jagannathan** [comment]
I used this nightly build, 
cling_2017-10-10_ec-ubuntu-14-04-x86-64-1

**Comment by Axel-Naumann** [comment]
The GCC 4.8 stdlib has no support for C++14. You'll need to move to a newer OS (or more difficult alternatives).
