### ISSUE TITLE
Full display of vectors of vectors

### ISSUE THREAD

**Issue by nthiery** [root-project/cling#187]
For introducing students to vectors in C++ [1], it's a really nice feature that vectors get displayed nicely in Cling:

```
[cling]$ vector<int> v = { 4, 5, 6 }
[cling]$ v
(std::vector<int> &) { 4, 5, 6 }
```

This lets them manipulate their vectors interactively and easily monitor how they evolve.

Sadly, for vectors of vectors, which are one step above for them to grasp, that feature is not available anymore. Only the address of the inner vectors are printed out:

```
[cling]$ vector<vector<int>> v = {{1,2},{3,4}};
[cling]$ v
(std::vector<std::vector<int> > &) { @0x476e0f0, @0x476e108 }
```
So they have to inspect each subvector one by one; in addition their long type makes them harder to read:
```
[cling]$ v[0]
(__gnu_cxx::__alloc_traits<std::allocator<std::vector<int, std::allocator<int> > > >::value_type &) { 1, 2 }
```

Is there a specific reason to just display addresses, or is it just not implemented, and you would consider a change to something like:
```
(std::vector<std::vector<int> > &) { {1, 2}, {3, 4} }
```

(and I guess, in general, displaying vectors and possibly other containers recursively).

Thanks,

Cheers,
                         Nicolas

cc: @gouarin, @SylvainCorlay

[1] Context: we have been using cling (via Jupyter+xeus-cling) for our
300 students [introductory C++ class](http://nicolas.thiery.name/Enseignement/Info111/)
this Fall. This was a bit of bleeding edge technology, but altogether
we believe it's been a very nice and engaging learning environment for
our students. Next year will be even better when the various glitches
will be ironed out.

**Comment by Axel-Naumann** [comment]
That's now working as one would expect:
```
[cling]$ #include <vector>
[cling]$ using namespace std;
[cling]$ vector<vector<int>> v = {{1,2},{3,4}};
[cling]$ v[0]
(std::vector<int, std::allocator<int> > &) { 1, 2 }
```

**Comment by nthiery** [comment]
Yippee!
Thank you so much; that will be so helpful for our students; and for those running from one to the other to help!

**Comment by Axel-Naumann** [comment]
Pleasure - thanks for teaching with cling! And let us know if you have ideas that could cater to your needs: for a couple of months during summer, we will have a student or two who can do some work on cling!

**Comment by SylvainCorlay** [comment]
woot!

**Comment by nthiery** [comment]
On Mon, Jan 15, 2018 at 04:31:42PM +0000, Axel Naumann wrote:
> And let us know if you have ideas that could cater to your needs:
> for a couple of months during summer, we will have a student or two
> who can do some work on cling!

Ah, good to know. I'll keep that in mind!
