### ISSUE TITLE
Configuring the display of the type of the outputs

### ISSUE THREAD

**Issue by nthiery** [root-project/cling#188]
C++ types can become rather long, which tends, when displaying outputs in cling, to bury down the actual value:

```
[cling]$ #include <vector>
[cling]$ using namespace std;
[cling]$ vector<vector<int>> v = {{1,2},{3,4}};
[cling]$ v[0]
(__gnu_cxx::__alloc_traits<std::allocator<std::vector<int, std::allocator<int> > > >::value_type &) { 1, 2 }
```
Is this something that could be improved or made configurable?

Just thinking out loud, here are some potential strategies:

- display the value first and then the type. So if one only cares about the value one can skip reading the type entirely
- In an environment like Jupyter+xeus-cling: visually highlight the type on one hand and the output on the other hand
- Shorten long types with ...
- (when the type is long), write the type and the output on two
  different lines; possibly with the value raged left and the type
  ragged right

I am not sure whether this is a question for cling in general, or
cling in Jupyter in particular.

cc: @gouarin, @SylvainCorlay

Context: see #187 for the teaching context. One reason we chose C++
over, e.g., Python is that we believe being explicit with types helps
our students better understand what they are calculating with. That in
addition clings displays the type of the outputs is quite a killer
feature for them. This also help teach them the distinction between
printing a value and returning a value.

However long types as above, which naturally pop up in C++ without
relating straightforwardly (for a beginner) to the input types, are
just confusing to them. The current display makes it hard for them to
skip them and focus on the value itself, which is the only piece of
information they actually can grasp at this stage.

**Comment by Axel-Naumann** [comment]
This should be much much better, actually - I get
```
(std::vector<int, std::allocator<int> > &) { 1, 2 }
```
as output. We actually decided to make it nice by default instead of configurable. Objections? :-)

**Comment by nthiery** [comment]
Nice by default is nice :-)
Thank you very much!
