### ISSUE TITLE
Jupyter kernel dead

### ISSUE THREAD

**Issue by HTLife** [root-project/cling#189]
When I open a c++17 notebook in jupyter, the kernel died immediately.

`The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened.`

The installation steps that I follow is: https://github.com/root-project/cling/tree/master/tools/Jupyter

**Comment by caiwan** [comment]
I followed the [xeus](https://github.com/QuantStack/xeus-cling) istructions, but I have the same result.

**Comment by ReneMoll** [comment]
It may be useful to attach the log.

I experienced the same problem after installing Jupyter & Cling. The log indicated an exception when starting the kernel: `pkg_resources.extern.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.` Which was solved by upgrading setuptools (`pip install --upgrade setuptools`)

**Comment by Axel-Naumann** [comment]
Without more info we cannot fix this. Please share the logs and I'll reopen.
