### ISSUE TITLE
Compile/Load library on Windows?

### ISSUE THREAD

**Issue by danhambleton** [root-project/cling#191]
So, I have successfully [compiled](https://github.com/MeshGeometry/cling-win) and tested cling on windows (Windows 10 x64). Writing some code works and it all seems fine. However, when I try to include a library:

```
cling .L C:/path/to/mylib.lib
```

I get a bunch of errors. There seem to by two main kinds. Initially, it outputs:

```
C:\Dev\cling-test\build\Release\api-test.lib:1:1: error: expected unqualified-id
!<arch>
^
```
and then I get many many lines of:

```
C:\Dev\cling-test\build\Release\api-test.lib:7:36: warning: null character ignored [-Wnull-character]
```

Any hints?

**Comment by bellenot** [comment]
You cannot load static libraries, only DLLs

**Comment by danhambleton** [comment]
Ah right, that makes sense.
So say I am trying to export a test function in a file called MyAPI.h:
```
#pragma once

#include <iostream>

extern "C"
{
	__declspec(dllexport) bool __cdecl SayHello();
	__declspec(dllexport) void __cdecl SayHelloA(){printf("Hello, there\n");};
}
```

When I compile this to a dll and load via `cling .L MyAPI.dll`, I don't get an error. However, running:
```
cling .I C:/Dev/cling-test
cling SayHello(); 
```
Gives me the error:
```
error: use of undeclared identifier 'SayHello'
```

Are there any compilation constraints that I'm missing? Is there a way to tell that the ".L" command worked?

**Comment by Masterxilo** [comment]
@danhambleton Did you try to include a header file containing `__declspec(dllimport)` directives first?

**Comment by danhambleton** [comment]
Hey, yes that does indeed work. It was totally a "between-chair-and-keyboard" issue :)
