### ISSUE TITLE
Typedef redefinition error when embedding cling on Win64

### ISSUE THREAD

**Issue by danhambleton** [root-project/cling#194]
So, when using the cling interpreter from the command line, I can run the following commands with no problem:

```
[cling]$ .L C:/Dev/Urho3D/Build/shared/bin/Urho3D.dll
[cling]$ .I C:/Dev/Urho3D/Build/shared/include
[cling]$ .I C:/Dev/Urho3D/Build/shared/include/Urho3D/ThirdParty
[cling]$ #include <Urho3D/Urho3DAll.h>
```

I have also successfully embedded cling in to my own exe (by following the example code). However, when I create the Interpreter and run those same commands like this:

```
	cling::Interpreter interp(argc, argv, LLVMDIR);
	interp.AddIncludePath(".");
	//load urho dll
	interp.loadLibrary("C:/Dev/Urho3D/Build/shared/bin/Urho3D.dll");
	interp.AddIncludePath("C:/Dev/Urho3D/Build/shared/include");
	interp.AddIncludePath("C:/Dev/Urho3D/Build/shared/include/Urho3D/ThirdParty");
	interp.loadHeader("Urho3D/Urho3DAll.h");
```

I get a bunch of type redefinition errors....

![image](https://user-images.githubusercontent.com/1939589/32984579-6f3b07da-cc77-11e7-96de-1575c190d938.png)

Any thoughts on this? I feel like I'm missing some preprocessor/compile flags.

**Comment by danhambleton** [comment]
Turns out these errors are caused by the Interpreter not "seeing" the cling include files. I think this is actually a bug, since setting the LLVM_DIR variable points the interpreter to the libs, but not the includes. To solve the issue, I put the cling folder containing the include files in the same directory as my app.

**Comment by Axel-Naumann** [comment]
I see. Can you share your CMakeCache.txt?

**Comment by danhambleton** [comment]
Sure, here it is.
[CMakeCache.txt](https://github.com/root-project/cling/files/1486126/CMakeCache.txt)

**Comment by danhambleton** [comment]
I rebuild recently and this issue seems to be fixed.

**Comment by Axel-Naumann** [comment]
Excellent, thanks!
