### ISSUE TITLE
inconsistency in registered CommandLine options

### ISSUE THREAD

**Issue by TrevorCash** [root-project/cling#201]
I have been trying to integrate the cling interpreter into my project on Ubuntu 16.04 LTS.

After building and installing the LLVM tree.  I successfully link my application. but on run-time I get the following error followed by a crash:

`: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options`

**Comment by Axel-Naumann** [comment]
This is usually caused by your application linking against llvm itself. That is actually possible, but you have to move cling into a shared library and link its llvm into it, statically. Then all of the cling library symbols must be hidden. Once you dlopen the cling library, cling will resolve symbols from it if you register the shared library handle with the llvm shared library system.

Let me know if I should collect code snippets from ROOT that show how to do it.

Cheers, Axel


________________________________

**Comment by TrevorCash** [comment]
Hi Axel-Naumann, 

I would love to see those snippets.

I have built llvm from http://root.cern.ch/git/llvm.git and then subsequently cloning clang and cling into the subdirectories with http://root.cern.ch/git/clang.git and http://root.cern.ch/git/cling.git while checking out the cling-patches branch on the clang repo.


In the cmake for the application target I have:

```
find_package(Cling CONFIG REQUIRED)

include_directories("/home/trevorcash/SDKs/LLVM/Release_Static/include")

# Define source files
define_source_files ()

#create exec
setup_main_executable ()
# links against clingInterpreter (and its dependencies).
target_link_libraries(Test clingInterpreter)

set_target_properties(Test
  PROPERTIES ENABLE_EXPORTS 1)

```

Thanks for the help! - Trevor

**Comment by Axel-Naumann** [comment]
That's fine, but you also link your binary against llvm? Do you need this - does your application use llvm or just cling?

The code I was thinking of is here: https://github.com/root-project/root/blob/master/core/base/src/TROOT.cxx#L2019 Not really that helpful - it's just the dlopen, and calling `cling::DynamicLibraryManager::ExposeHiddenSharedLibrarySymbols(clingLibHandle);` as done here https://github.com/root-project/root/blob/master/core/metacling/src/TCling.cxx#L619

But again - you shouldn't need that unless your program uses clang or llvm itself, independently of those used by cling.

**Comment by Axel-Naumann** [comment]
No response, I suppose it got self-solved.

**Comment by dilevin** [comment]
I'm also running into a variant of this bug related to the problem that Mesa dynamically links LLVM (thanks for the reproducer here: https://github.com/Axel-Naumann/llvm-mesa-reproducer). Is there an easy fix for this ? 

I'm compiling using the latest GCC on Ubuntu 18.04.

**Comment by Axel-Naumann** [comment]
We use
```
  set(CMAKE_CXX_VISIBILITY_PRESET hidden)
  set(CMAKE_C_VISIBILITY_PRESET hidden)
```
in our configuration of llvm and clang; that should do the trick.

**Comment by BorisVassilev1** [comment]
I am getting the same error when linking dynamically to `libcling.so` on Arch. Hiding the symbols in the executable does not change the error.

I am embedding cling in a program. I want to link with cling dynamically. Is `libcling` the right thing to use or should I somehow link only to clingInterpreter and its dependencies?
