### ISSUE TITLE
How to access static function of class in host app?

### ISSUE THREAD

**Issue by danhambleton** [root-project/cling#202]
So, I have embedded cling in to my app. Everything is working well. In particular, I can compile this class:
```
class MyClass : public LogicComponent
{

public:
	float mTotalTime;

	MyClass(Context* context) : LogicComponent(context),
	mTotalTime(0.0f)
	{
		printf("Hello from Fields!");
	}

	~MyClass(){};	
	static void RegisterComponent(Context* context)

	{
	    context->RegisterFactory<MyClass>();
	}

	virtual void Update (float timeStep) {
		mTotalTime += timeStep;
		GetNode()->SetScale(0.5f * Sin(20.0f * mTotalTime));
	}
};

```

I now need to register this class with my host application (in particular the Context*). To do this, I would like to call `RegisterComponent` using something like:
```
void* addr = mInterpreter->getAddressOfGlobal("RegisterComponent");
using func_t = void(Context*);
func_t* pFunc = cling::utils::VoidToFunctionPtr<func_t*>(addr);
```
However, this doesn't work because RegisterComponent is a not a global. Can I get the address of such a function?

**Comment by Axel-Naumann** [comment]
`RegisterComponent` is really `MyClass::RegisterComponent`. And that's mangled; you'll need to look it up using its mangled name.

Alternatively, create an `extern "C"` wrapper function whose only job is to invoke `MyClass::RegisterComponent`. The advantage of the `extern "C"` function is that there's no mangling. See e.g. https://github.com/root-project/root/blob/master/interpreter/cling/tools/demo/cling-demo.cpp#L51
