### ISSUE TITLE
/usr/include/wchar.h:89:10: fatal error: 'stdarg.h' file not found

### ISSUE THREAD

**Issue by kdheepak** [root-project/cling#203]
When I try to run the following simple command in cling,

```cpp
#include <iostream>
```

it works fine.

![screen shot 2017-12-20 at 12 53 14](https://user-images.githubusercontent.com/1813121/34225542-0da9ddc2-e584-11e7-8cb4-a22acea81ce0.png)

However, running the same thing in a jupyter notebook with the cling kernel throws an error.

![screen shot 2017-12-20 at 12 53 44](https://user-images.githubusercontent.com/1813121/34225562-1e4a5c88-e584-11e7-824e-056dbb56fd46.png)

Any suggestions on how to solve this?

**Comment by Axel-Naumann** [comment]
Could you run `xcode-select --install`?

**Comment by kdheepak** [comment]
I get the following

```bash
xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by Axel-Naumann** [comment]
What's the output of `.I` in the notebook?

**Comment by Axel-Naumann** [comment]
No response, I suppose it got self-solved.

**Comment by doself** [comment]
hey，I have a same problem in Jupyter-notebook，how to solve this?

**Comment by mrexodia** [comment]
Running into this issue now on macos 12.6 (M1 Pro). I ran `brew install cling` and the output of `.I` is:

```
-isysroot
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/
-I
/opt/homebrew/Cellar/cling/0.9/include/
-cxx-isystem
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1
-isystem
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include
-isystem
lib/clang/9.0.1/include
-extern-c-isystem
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
-I
/opt/homebrew/Cellar/cling/0.9/libexec/include
-I
/tmp/cling-20211028-25253-1lx6xi/src/tools/cling/include
-I
/tmp/cling-20211028-25253-1lx6xi/src/tools/clang/include
-I
/tmp/cling-20211028-25253-1lx6xi/build/tools/clang/include
-I
/Users/admin/.asdf/installs/python/3.10.6/include
-resource-dir
lib/clang/9.0.1
-nostdinc++
-stdlib=libc++
```

Previously when I encountered this the problem was related to the `-resource-dir` not being correct. The issue was here: https://github.com/MaskRay/ccls/issues/853. How would I modify the include paths?

**Comment by mrexodia** [comment]
It looks like running: `.include /opt/homebrew/Cellar/cling/0.9/libexec/lib/clang/9.0.1/include` fixes things!

**Comment by L4rralde** [comment]
Hi, @mrexodia. I installed cling in m1 air.  What do you mean with the following?
> running: .include /opt/homebrew/Cellar/cling/0.9/libexec/lib/clang/9.0.1/include

Thanks!

**Comment by mrexodia** [comment]
> Hi, @mrexodia. I installed cling in m1 air. What do you mean with the following?
> 
> > running: .include /opt/homebrew/Cellar/cling/0.9/libexec/lib/clang/9.0.1/include
> 
> Thanks!

You run that command in the REPL to adjust cling's internal state. Afterwards things will work.
