### ISSUE TITLE
Build cling at raspberry P3

### ISSUE THREAD

**Issue by wangmu0579** [root-project/cling#206]
Hi, everyone:
  I have installed LLVM  using apt-get install llvm at raspberry P3 successful.
 Anyone know how to build cling which based on the LLVM I installed but not build the llvm using source code? Maybe that's means how to change Makefile. 
 Because PI 3 only have 1 GB mem which may leads to build llvm failed.

**Comment by Axel-Naumann** [comment]
cling needs a specific version of llvm (5.0). And on top of that, cling needs its very own patched clang, and that's the biggest chunk of code to build.

I'd recommend to cross-compile. Or else
- configure to build without debug symbols
- `make -j1` (i.e. no concurrent build processes)
