### ISSUE TITLE
Inconsistent Jupyter Kernel install instructions

### ISSUE THREAD

**Issue by lwolfsonkin** [root-project/cling#210]
In [the readme](https://github.com/root-project/cling#jupyter), the instructions to install the `cling` `jupyter` kernel with `jupyter kernelspec install cling` is incorrect and does not work, though the instructions in [tools/Jupyter](https://github.com/root-project/cling/tree/master/tools/Jupyter#install) are fine.

**Comment by Axel-Naumann** [comment]
Thanks, fixed by 681e0c5
