### ISSUE TITLE
Exit cling after pressing Control-D

### ISSUE THREAD

**Issue by saagarjha** [root-project/cling#212]
In most interactive programs, <kbd>Control</kbd>+<kbd>D</kbd> is handled as an end-of-file, causing the program to exit. However, in cling <kbd>Control</kbd>+<kbd>D</kbd> appears to be completely ignored. Is this intended behavior?

**Comment by Axel-Naumann** [comment]
We'd welcome a pull request that causes cling to exit if <kbd>Ctrl</kbd>+<kbd>D</kbd> is pressed on an *empty* line!

**Comment by saagarjha** [comment]
Wow, that was fast! I'll see what I can do; it might take a bit to get cling to compile on my machine so I can test it.

**Comment by saagarjha** [comment]
I'm sorry, but I'm having troubles figuring out how to build cling. If I clone this repository and run CPT it seems to create a packaged version, and I follow [these build instructions](https://root.cern.ch/cling-build-instructions) I get build failures because it seems to be pulling in incompatible versions of llvm and clang. How should I be doing this?

**Comment by Axel-Naumann** [comment]
What errors do you see the the instructions from https://root.cern.ch/cling-build-instructions ? They seem correct...

**Comment by saagarjha** [comment]
Something about not being able to find `SectionEntries`, which is defined in relatively recently. Following those instructions, it seems like I got a new version of clang but an old version of llvm.

Also, is http://root.cern.ch/git/cling.git a mirror of this repository?

**Comment by Axel-Naumann** [comment]
Are you sure both llvm.git and clang.git are switched to the cling-patches branch?

**Comment by saagarjha** [comment]
Just recloned and performed a fresh build and it looks like it finished compiling successfully. I couldn't figure out why it failed the first time, but after a bit of sleuthing in my terminal's scrollback buffer it seems like the `git checkout` failed for whatever reason and I just hadn't noticed it. Sorry for bothering you!

I was taking a look at the handling of the behavior of the other Control key commands (namely, <kbd>Control</kbd>+<kbd>C</kbd> and <kbd>Control</kbd>+<kbd>Z</kbd>) and noticed that <kbd>Control</kbd>+<kbd>C</kbd> doesn't act quite like it does in other interactive shells. Here's what behavior currently looks like in Cling:

```shell
$ cling

****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
[cling]$ some text // Control-C pressed here, right after entering some text
$
```
and in another program:
```shell
$ some-interactive-program # eg Bash, LLDB, GDB, etc.
> some text^C # Control-C pressed here, right after entering some text
> ^C # Control-C pressed with no text
> ^C # Again…
> ^D # Control-D pressed for EOF
$
```

Should I try to match this behavior?

**Comment by Axel-Naumann** [comment]
Yes please!

**Comment by saagarjha** [comment]
I actually forgot about this issue for a while; sorry about that. I took another look at it and realized that I wanted to ask you about how to structure this. Is there any API that I can use that does something like adding text to the current line, or leave the line unevaluated? I spent a bit of time looking at this but I didn't find anything that really worked for the situation here.

**Comment by Axel-Naumann** [comment]
I think we could just add a `signal` handler in `lib/UserInput`. That can ask its `textinput` for the length of the current prompt text. Would that do?

**Comment by saagarjha** [comment]
Yeah, I currently have a "signal handler" set up for these–however, I can't figure out how to emulate the specific behavior that readline does. In particular, when I perform a <kbd>Control</kbd>+<kbd>C</kbd>, I need to put a "^C" at the end of the line and then advance to the next prompt without evaluating it. <kbd>Control</kbd>+<kbd>D</kbd> does nothing on a non-empty line, and exits on an empty one (I already have this mostly working, I think).

**Comment by Axel-Naumann** [comment]
- You should be able to modify `TextInput`'s current input text. Let me know if I need to find out / remember how this would work :-)
- `lib/UserInterface` does that "loop" part of "REPL"; you should be able to "continue" for <kbd>Ctrl</kbd>+<kbd>C</kbd>

**Comment by saagarjha** [comment]
See #243.

**Comment by Axel-Naumann** [comment]
Thanks for your PR!
