### ISSUE TITLE
Define and initialiation array error!

### ISSUE THREAD

**Issue by liudonghua123** [root-project/cling#218]
![image](https://user-images.githubusercontent.com/2276718/37378075-a6286cb4-2768-11e8-8268-ea8dbb2ecc19.png)

**Comment by danhambleton** [comment]
Yes, I'm getting this too!

**Comment by TrevorCash** [comment]
I get this as well on Windows compiling with MSVC.

**Comment by bellenot** [comment]
Can you try to add the missing symbols (the mangled ones) in the cling_exports list in tools/driver/CMakeLists.txt, and rebuild, to see if it solves the issue?

**Comment by danhambleton** [comment]
Yep, adding the symbol fixes the error. Thanks!

**Comment by bellenot** [comment]
@liudonghua123 and @TrevorCash could you confirm this fixes the issue?
FYI, I created a PR fixing this issue (and a couple more)

**Comment by liudonghua123** [comment]
I updated the code and applied the patches on [this issue](https://github.com/root-project/cling/issues/200), but When I run a fresh build, I faced another [issue](https://github.com/root-project/cling/issues/223).

**Comment by liudonghua123** [comment]
BTW, How can I find the missing symbols related to this issue as the snapshot shown.

**Comment by bellenot** [comment]
see [this PR](https://github.com/root-project/cling/pull/221)

**Comment by bellenot** [comment]
@liudonghua123 If this issue is fixed, could you close it? Thanks!

**Comment by liudonghua123** [comment]
Thank you @bellenot , it works now.

**Comment by bellenot** [comment]
FYI, everything is now fixed in the master
