### ISSUE TITLE
Provide accessor to the `InputValidator` attribute of the meta-processor

### ISSUE THREAD

**Issue by SylvainCorlay** [root-project/cling#226]
The Jupyter Protocol requires checking whether an input is complete in a separate message from the execution request, while the current cling API is such that the process function returns the indentation level.

It the InputValidator was exposed, or at least a new method was provided to the meta-processor indicating whether a provided input code is complete, we could tackle this requirement of the Jupyter protocol.

(originally posted here: https://github.com/vgvassilev/cling/issues/182)

**Comment by SylvainCorlay** [comment]
Note that the `is_complete_[request/reply]` jupyter messages and indentation levels are only used for console-type frontends, and not by the notebook. However, a console interface is present in JupyterLab.

Making this API public would allow us to have much better behavior for the kernel:

![cling-console](https://user-images.githubusercontent.com/2397974/38779902-26397d42-40cf-11e8-924e-e392dfa21c89.gif)

**Comment by Axel-Naumann** [comment]
No objections against that change. Can you suggest a PR?

**Comment by SylvainCorlay** [comment]
Thanks! I will do.

**Comment by SylvainCorlay** [comment]
This was fixed in #267.
