### ISSUE TITLE
Document how to set up cling with a project that uses CMake

### ISSUE THREAD

**Issue by balta2ar** [root-project/cling#23]
Moving suggestion from another issue here: https://github.com/root-mirror/cling/issues/12#issuecomment-233895885

The idea is to document the following steps:
1. Choose a C++ project that uses CMake as its build system
2. Adjust build scripts to generate precompiled headers as suggested here: https://github.com/root-mirror/cling/issues/12#issuecomment-233880736
3. Show how to run cling with these headers
4. Do something simple in cling to demonstrate that it's working.

This should allow new users of cling to start using it faster and easier.

**Comment by karies** [comment]
I have pushed an update to the cling web pages - maybe we can get a pull request for use.html?

**Comment by balta2ar** [comment]
Sure, I will do my test once I figure out how to create pch files with CMake! In the meanwhile, where can I look at these pages in a browser? I mean not HTML source code but an actual page.

**Comment by karies** [comment]
See https://cdn.rawgit.com/root-mirror/cling/master/www/index.html - I have updated cling's README.

**Comment by Axel-Naumann** [comment]
I have pushed tools/demo: a simple CMake project using cling. I don't think a PCH qualifies for "simple"; then again building a PCH with cling is expected to change in the near future - so I'll leave this part untouched for now.
