### ISSUE TITLE
NVRTC support

### ISSUE THREAD

**Issue by DavidPoliakoff** [root-project/cling#234]
This references a fun conversation with @ax3l and @SimeonEhrig on #115 .

I look forward to Cling supporting CUDA, but it currently doesn't. While waiting on that I thought I'd use [Jitify](https://github.com/NVIDIA/jitify), a layer over NVRTC, from within a Cling Notebook. However, it turns out that Jitify also errors out. Here is the program I attempted to run

```
#include<jitify.hpp>
const char* program_source1 = "my_program\n __global__\n void my_kernel() {\n }\n";
static jitify::JitCache kernel_cache;
dim3 grid(1);
dim3 block(1);
jitify::detail::vector<std::string> nothing;
jitify::Program program = kernel_cache.program(program_source1, nothing, nothing);
program.kernel("my_kernel").instantiate();//.configure(grid,block).launch();
```

This goes smoothly through PTX creation, printing out valid PTX [here](https://github.com/NVIDIA/jitify/blob/master/jitify.hpp#L2252), but then crashes somewhere within [this module creation code](https://github.com/NVIDIA/jitify/blob/master/jitify.hpp#L921).

To recreate, launch Cling with

```
cling -I<Jitify Dir> -I<CUDA include dir> -L<Cuda Toolkit Lib Dir> -L<libcuda.so dir (typically /usr/lib64>) -DJITIFY_PRINT_ALL -lcuda -lnvrtc -lcudart
```

and then run the program I put in comments. If all goes as it did for me you'll get PTX output followed by

```
terminate called after throwing an instance of 'cling::InvalidDerefException'
  what():  Trying to dereference null pointer or trying to call routine taking non-null arguments
```

Within cling::Interpreter::RunFunction

Let me know if you need any other info, your project is awesome!

**Comment by DavidPoliakoff** [comment]
Pinging @benbarsdell and asking him to ping Kate (I don't have her Github username) as they've apparently seen this, they're the Jitify devs, and like all JIT people they're great. I did a little more digging, and we're dying at [this](https://github.com/NVIDIA/jitify/blob/master/jitify.hpp#L844) particular line.

**Comment by maddyscientist** [comment]
Kate me

**Comment by benbarsdell** [comment]
It doesn't seem to like `&_opts[0]` [here](https://github.com/NVIDIA/jitify/blob/master/jitify.hpp#L842). Replacing it with `_opts.data()` seems to work. The same also needs to be done for `&arg_ptrs[0]` -> `arg_ptrs.data()` [here](https://github.com/NVIDIA/jitify/blob/master/jitify.hpp#L940). After these changes it runs through for me.

**Comment by DavidPoliakoff** [comment]
@benbarsdell : this is amazing. That's enabling some stuff we just outright could not do before. I'll test it out more, but @ajkunen @trws @davidbeckingsale, apparently there is a path to Jitify+Cling

**Comment by ax3l** [comment]
Wow, that is fantastic news!! Thank you all for fixing this so quickly!

**Comment by DavidPoliakoff** [comment]
I think if your two groups collaborate, really impressive things could happen. I'll close this, there's an email thread you hopefully received @ax3l . Great work, folks

**Comment by ax3l** [comment]
Yes, I am on it, exciting times ahead indeed!
