### ISSUE TITLE
cling does not support Jupyter+Tornado>=5.x

### ISSUE THREAD

**Issue by jhgoebbert** [root-project/cling#236]
Hi,

it seems as if the cling Jupyter-kernel does not support Jupyter, which is based on Tornado>=5.x:
_[...] instance must be a ZMQIOLoop, but a value of class 'tornado.platform.asyncio.AsyncIOMainLoop' [...]_

Thank you for the great compiler!
Best,
Jens Henrik

**Comment by ax3l** [comment]
Hi Jens,

I think that's not a cling issue but a general jupyter notebook dependency issue. See e.g. https://github.com/conda-forge/notebook-feedstock/issues/31

Looks to me like Jupyter 5.3.0+ contain the fix: https://github.com/jupyter/notebook/pull/3034

**Comment by jhgoebbert** [comment]
Hi Axel,

I rebuild all dependencies with GCC 5.5.0 again and it works fine now.
Sorry for the wrong interpretation of the error message and
thanks a lot for the good hint !!

Best,
Jens Henrik

-------------------------------------------------------------------------------------
Dipl.-Ing. Jens Henrik Goebbert
Jülich Supercomputing Centre (JSC)
Wilhelm-Johnen-Straße, 52425 Jülich, Germany
phone: +49 2461 61-96498
email: j.goebbert@fz-juelich.de<mailto:jh.goebbert@fz-juelich.de>

________________________________

**Comment by ax3l** [comment]
You are welcome! Just saw it by coincidence and thought it might help you :)

Best wishes from HZDR,
Axel

**Comment by ax3l** [comment]
@jhgoebbert feel free to close the issue if this solves it for you.
