### ISSUE TITLE
Workflow and Documentation of Exact Branching Points

### ISSUE THREAD

**Issue by ax3l** [root-project/cling#237]
Dear  @vgvassilev and @Axel-Naumann,

can we document for each tagged (versioned) releases of cling the following information please?

- **llvm**
  - *base tag* (and/or *commit*) where you branch from mainline (https://git.llvm.org/git/llvm)
  - patch range from which *branch* in (http://root.cern.ch/git/llvm.git) to apply
- **clang**
  - *base tag* (and/or *commit*) where you branch from mainline (https://git.llvm.org/git/clang)
  - *patch range* from which *branch* in (http://root.cern.ch/git/clang.git) to apply

I am trying to bring cling into [spack](https://github.com/spack/spack/issues/4668). The LLVM eco-system of tools is complex and a user often not only needs cling & clang but even more tools from LLVM in a consistent state.

This includes, last but not least, a full software tree on top of it as well, e.g. HDF5, MPI, [PIConGPU](https://github.com/ComputationalRadiationPhysics/picongpu/), ... which I might want to pre-build with *the same, matching, clang version* before using all of this in my cling jupyter notebooks on a high level. For this to work, we need to fit the cling "llvm tool" naturally in it's surroundings and should ideally branch off cling-releases and patches from *stable llvm releases* (just think about compiler-work-arounds in software stacks for example that check clang versions).

It would be awesome if you could document the information above, e.g. as an advanced section in https://root.cern.ch/cling-build-instructions This would make a packagers life so much easier. We don't need to document all former releases, but maybe the last stable release and all upcoming?

I am thinking of some table like (information below are just examples):

| cling release | llvm base           | patches needed                       | clang base           | patches needed                       |
|---------------|---------------------|--------------------------------------|----------------------|--------------------------------------|
| 0.4.0         | 4.0.0               | asdasdsa..saddasd in `cling-patches` | 4.0.0                | 2sda1dsa..3adda5d in `cling-040-patches` |
| 0.5.0         | 5.0.0               | *none*                               | 5.0.0                | dsadsahs..3rg56uf in `cling-050-patches` |
| master        | 5.0.0-312-7w4sak     | *none*                               | 5.0.0-234-adsad      | dsadsahs..3rg56uf in `cling-patches` |

Probably directly in the `README` of this repo since you can update is as you update your requirements in one go (and on top of this it makes sense in the official build instructions linked above).

Thanks a lot for considering!

**Comment by Axel-Naumann** [comment]
We can certainly do that.

Since the last cling release we have started branching off stable llvm releases. I have updated https://root.cern.ch/cling-build-instructions accordingly. Let me know whether that addresses your needs.

**Comment by Axel-Naumann** [comment]
> a typo

Fixed!

Development: this is a bit awkward, as it's subject to change and I am certain that we will fail to keep this page up to date, at least outside of releases. Do you mind determining what clang.git's `cling-patches` corresponds to yourself? These days it's fairly easy to decompose the different parts:
- look at cling/LastKnownGood.txt and get its llvm + clang (or later, in the same release branch)
- check what clang.git's `cling-patches` corresponds to.
