### ISSUE TITLE
Better compileFunction error returns

### ISSUE THREAD

**Issue by DavidPoliakoff** [root-project/cling#238]
Hey folks,

I wrote a really long issue about how compileFunction was clearly broken, and that it couldn't be _my_ code, when I had in fact just spelled the name of a function wrong (oops). It would be nice if we had some way to better determine what failed, and I imagine you'll save a fair number of migraines from erroneous issues as well.

**Comment by Axel-Naumann** [comment]
PR welcome! Or at least a sketch of the wanted behavior...

**Comment by DavidPoliakoff** [comment]
Hey folks, I wound up getting horribly sidetracked after posting this, I'll close this as part of a bug cleanup
