### ISSUE TITLE
Kernel crashes with a 10Mb array

### ISSUE THREAD

**Issue by sergeny** [root-project/cling#251]
I have tried implementing the Eratosthenes sieve for finding all prime numbers up to 10,000,000.

My conclusions:
* it is slower than doing the same with python + numba
* it works for the primes up to 8 million, but the kernel dies when going to 10 million and restarts automatically.
I have 8Gb of memory, and I expect 10 million bools to take 10 Mb when using C++.

```
#include <iostream>
#include <chrono>

using namespace std;

/////// another cell

namespace p {
        void compute_primes(bool * is_prime, int N) {
            memset(is_prime, 0xFF, N);
            is_prime[0] = false;
            is_prime[1] = false;
        
            int prime_count = 0;
            for (int i = 2; i < N; i++) {
                if (is_prime[i]) {
                    prime_count++;
                }
                //is_prime[i] = true;
                int k = i + i;
                while (k < N) {
                    is_prime[k] = false;
                    k += i;
                }
            }            
        };
};

/////// another cell

// Need the lambda function to be able to rerun the cell multiple times.
// Otherwise, of course, it cannot redefine variables in C++.
[](){
    // Record start time
    auto start = std::chrono::high_resolution_clock::now();

    const int N=9000000; // Ok with 8,000,000. Dies with 10,000,000.
    bool is_prime[N];
    p::compute_primes(is_prime, N);

    // Record end time
    auto finish = std::chrono::high_resolution_clock::now();

    std::chrono::duration<double> elapsed = finish - start;
    cout << elapsed.count() << " seconds elapsed";
}();
```

**Comment by asgeir** [comment]
Are you sure you didn't just explode your stack? On my machine if I `cat /proc/self/limits` I can see a soft limit of 8388608 bytes for stack size, which I believe is the default for pthreads.

**Comment by sergeny** [comment]
@asgeir , 
indeed, I've tried setting "ulimit -s 65000", and then it would only crash around 60-something million.

Then I took the variable out of the lambda function, and now it doesn't crash even at 200 million. Thus, you have solved the issue!

The two remarks I have are,
- it is harder to debug if I have to declare large variables outside of a lambda function, as then I have to restart the kernel and rerun the entire notebook every time. A solution is declaring large valuables on top and not rerunning this cell. You can still modify the code in a given lambda function, and then pass all the large variables involved to that lambda function. So that still gives enough interactivity. 

In the example above,

```
const N=100000000;
bool is_prime[N];

/// next cell

[](bool * is_prime) {
  ...  // this code can be edited and rerun interactively
}(is_prime);
```

- the execution is still significant slower than what I get with python + numba, about 10x slower. Unsure, why or what can be done about that.

**Comment by sergeny** [comment]
Allocating storage on the heap works. At least, with 
```
bool * is_prime = new bool[N];
.... // do things
delete[] is_prime;
```

Unfortunately, it still has the same (slower) peformance. However, I have tried the C++ shell from the full installation of the CERN's ROOT project, https://root.cern.ch/ , and there I do get performance comparable to that of numba-optimized code.  But I don't get it in jupyter with xeus-cling, which is what I have been using.

**Comment by Axel-Naumann** [comment]
...and we're not even optimizing JITed code yet - `-O2` is hopefully coming in the next month.

**Comment by Axel-Naumann** [comment]
And thanks for confirming that it's solved!
