### ISSUE TITLE
some errors at starting leads to command failure

### ISSUE THREAD

**Issue by heyAyushh** [root-project/cling#255]
In file included from input_line_1:1:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/new:91:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/exception:82:
In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/cstdlib:86:
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdlib.h:94:15: fatal error: 'stdlib.h' file not found
#include_next <stdlib.h>
              ^~~~~~~~~~
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with _LIBCPP_VERSION '4000'
  Extraction of runtime standard library version was: '6000'

**Comment by Axel-Naumann** [comment]
Thanks, @heyAyushh :-) Glad to see it's fixed!
