### ISSUE TITLE
Please allow to use external llvm and clang

### ISSUE THREAD

**Issue by yurivict** [root-project/cling#256]
We already have external llvm and clang installed.
Yet, cling installs its own copies of them.
How to use the pre-installed, external llvm and clang?

**Comment by LoganDark** [comment]
Not all versions of LLVM and Clang are compatible. Additionally, I think Cling uses modified versions (correct me if I'm wrong).

**Comment by ferdymercury** [comment]
Yes, for cling to work, you need some specific patches on top of clang, so not possible to use the pre-installed ones. More info: https://root-forum.cern.ch/t/compiling-root-6-24-with-external-llvm-but-built-in-clang/45258/7

You can consider instead using `clang-repl` which is part of LLVM.
