### ISSUE TITLE
Question: How to fix tests and merge?

### ISSUE THREAD

**Issue by datacabinet** [root-project/cling#273]
Can someone please tell me how I can fix the tests on this pull request? 

https://github.com/root-project/cling/pull/272

The CI tests failed. Can I please get some help from someone better versed in this codebase?

**Comment by Axel-Naumann** [comment]
Help finally arrived - but the Travis CI infra is still broken. I'll leave this open until it's fixed. Apologies that this took - unacceptably - long.

**Comment by Axel-Naumann** [comment]
https://github.com/root-project/cling/pull/301 shows that travis is back. We need ccache to do its job - so a couple of builds will still fail, until we have collected enough build artifacts that travis doesn't time out the builds. But from the `.travis` point of view the PR builds should work now!

Thanks for your report!
