### ISSUE TITLE
CMake error with LLVM 7

### ISSUE THREAD

**Issue by scalpel4k** [root-project/cling#274]
Hi,

I can't compile cling against LLVM 7 because of a cmake error.

[   65s] CMake Error at tools/driver/CMakeLists.txt:115 (target_link_libraries):
[   65s]   The keyword signature for target_link_libraries has already been used with
[   65s]   the target "cling".  All uses of target_link_libraries with a target must
[   65s]   be either all-keyword or all-plain.
[   65s] 
[   65s]   The uses of the keyword signature are here:
[   65s] 
[   65s]    * /usr/lib64/cmake/llvm/LLVM-Config.cmake:90 (target_link_libraries)
[   65s]    * /usr/lib64/cmake/llvm/AddLLVM.cmake:795 (target_link_libraries)

**Comment by FirstLoveLife** [comment]
Same error here

**Comment by gracicot** [comment]
I fixed the problem by adding this to `cling/tools/driver/CMakeLists.txt`:
```diff
+++ b/tools/driver/CMakeLists.txt
@@ -112,7 +112,7 @@ if(MSVC)
 
 endif(MSVC)
 
-target_link_libraries(cling
+target_link_libraries(cling PUBLIC
```

**Comment by Axel-Naumann** [comment]
You cannot mix and match llvm vs cling. Cling currently builds against llvm v5; we plan to upgrade by the end of the year.
