### ISSUE TITLE
Overlinking of zlib

### ISSUE THREAD

**Issue by SylvainCorlay** [root-project/cling#277]
Hello, I wanted to give you a heads up that cling appears to be overlinking `zlib`, which is reported by the conda-build tooling.

There are probably two dependencies depending on it, one linking statically and the other one linking dynamically.

**Comment by Axel-Naumann** [comment]
Thanks, Sylvain. We had a couple of changes in this area recently, is conda still showing this issue?

**Comment by SylvainCorlay** [comment]
It does not seem so. Closing.
