### ISSUE TITLE
LLVM_CONFIG on visual studio installation

### ISSUE THREAD

**Issue by IlanHindy** [root-project/cling#278]
Hi,
My perpouse is to activate cling with Jupyter. On windows with Miniconda.
I downloaded the source to visual studio and tried to compile it.

I got the following error 👍 

> Error		CMake Error at C:\Users\IlanH\Source\Repos\cling\CMakeLists.txt:42 (message):
>   llvm-config not found -- LLVM_CONFIG-NOTFOUND	Cling	C:\Users\IlanH\Source\Repos\cling\CMakeLists.txt	42	
>  
I have LLVM on my computer but I could not find in the installation a file named llvm-config. 
I have in my Miniconda files named LLVM_config.cmake (probably created there because of false installation of xeus-cling) can I use it?
Is there a place where there are detaied instructions on how to compile cling on Visual-studio?
Ilan

**Comment by Axel-Naumann** [comment]
How exactly did you try to compile it?

**Comment by lpxnvk** [comment]
@Axel-Naumann 
```
C:\Users\bakslop\Desktop\1111\cling\cmk_build>cmake .. -G"NMake Makefiles"
-- The C compiler identification is MSVC 19.25.28614.0
-- The CXX compiler identification is MSVC 19.25.28614.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:42 (message):
  llvm-config not found -- LLVM_CONFIG-NOTFOUND


-- Configuring incomplete, errors occurred!
See also "C:/Users/bakslop/Desktop/1111/cling/cmk_build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/bakslop/Desktop/1111/cling/cmk_build/CMakeFiles/CMakeError.log".
```

**Comment by ferdymercury** [comment]
Please try to follow these more up to date instructions: https://root-forum.cern.ch/t/compiling-cling-on-windows-msvc-2022/47106/17?u=ferhue
