### ISSUE TITLE
WSL - compile failed

### ISSUE THREAD

**Issue by rsrini7** [root-project/cling#279]
Installed using : https://raw.github.com/karies/cling-all-in-one/master/clone.sh

Actual error:
In file included from /home/rsrini/cling/src/tools/lli/lli.cpp:30:
/home/rsrini/cling/src/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h: In member function ‘llvm::Expected<std::vector<char> > llvm::orc::remote::OrcRemoteTargetClient<ChannelT>::readMem(char*, llvm::JITTargetAddress, uint64_t)’:
/home/rsrini/cling/src/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h:722:26: error: could not convert ‘((llvm::orc::remote::OrcRemoteTargetClient<ChannelT>*)this)->callB<llvm::orc::remote::OrcRemoteTargetRPCAPI::ReadMem>(Src, Size)’ from ‘Expected<vector<unsigned char,allocator<unsigned char>>>’ to ‘Expected<vector<char,allocator<char>>>’
     return callB<ReadMem>(Src, Size);
            ~~~~~~~~~~~~~~^~~~~~~~~~~

Complete compilation logs: https://pastebin.com/ytU0CfjT

rsrini@MSI:~/cling$ obj/bin/cling

****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
`[cling]$ #include <iostream>`
`[cling]$ using namespace std;`
`[cling]$ cout << "srini hi";`
In file included from input_line_3:1:
In file included from /usr/include/c++/8/iostream:39:
/usr/include/c++/8/ostream:559:8: error: no member named 'setstate' in 'std::basic_ostream<char>'
        __out.setstate(ios_base::badbit);
        ~~~~~ ^
input_line_6:2:7: note: in instantiation of function template specialization 'std::operator<<<std::char_traits<char> >' requested here
 cout << "srini hi";
      ^
[cling]$ .q

**Comment by Axel-Naumann** [comment]
That should be fixed in the master - please complain if not and I'll re-open.
