### ISSUE TITLE
Need help about installation

### ISSUE THREAD

**Issue by defydahui** [root-project/cling#281]
I used following command to install cling in Windows 7:
python ./cpt.py --create-dev-env Debug --with-workdir=cling-build --with-llvm-url=https://github.com/llvm-mirror/llvm --with-clang-url=https://github.com/llvm-mirror/clang --with-cling-url=https://github.com/root-project/cling --with-workdir=cling-build --current-dev=branches:master,master,master  --with-cmake-flags="-DCMAKE_INSTALL_PREFIX"
but it failled with lots of compile error, when compiling cling.
One error is "can not find file 'clang\Frontend\CodeGenOptions.h'".
Another is "cling::DeclCollector::HandleInvalidTagDeclDefinition”: “final” should be virtual function.
Can any one give some help?

**Comment by Axel-Naumann** [comment]
Please don't provide the clang and llvm urls; they do not have the required branches.
