### ISSUE TITLE
'addOverlay': is not a member of 'clang::CompilerInvocation'

### ISSUE THREAD

**Issue by LegalizeAdulthood** [root-project/cling#285]
I was supposed to talk about cling tonight in my user group meeting as part of a discussion on interactive C++ tools.  However, once again, cling doesn't have prebuilt Windows releases and doesn't build out of the box:

```
(ClCompile target) ->
  c:\code\cling\zip\build\cling-src\tools\cling\lib\interpreter\interpreter.cpp(309): error C2039: 'addOverlay': is not a member of 'clang::CompilerInvocation' [C:\Code\cling\zip\build\builddir\tools\cling\lib\Interpreter\obj.clingInterpreter.vcxproj]
```

I unzipped the 0.5 release and ran cpt.py in tools/packaging.  After much grinding, it gets an error compiling.  If I comment out the offending line, it then gets an error linking saying it can't find ~raw_ostream.  I see that LLVMSupport is a proper dependency of cling, so I don't know why it doesn't find ~raw_ostream.

You need to use git more sensibly to ensure that your releases actually compile and link, either by using git modules or actually forking the necessary stuff in github and making a feature branch.

This happened to me the last time I tried to evaluate cling.  It has potential, but the way you're managing your releases and your source code is really prohibitive to letting people try it.  It's not like Windows is some obscure OS that noone uses.

**Comment by LegalizeAdulthood** [comment]
By "forking stuff", I am referring to forking the LLVM/clang repositories so that cling is a feature branch on top of LLVM/clang.

**Comment by Axel-Naumann** [comment]
Does the current master of cling + `cling-patches` of root.cern/git/llvm.git , root.cern/git/clang.git work for you? (How's that not "forking the necessary stuff in github and making a feature branch"?)

If things suck, please contribute to make it work better!

**Comment by Axel-Naumann** [comment]
No response, I don't know waht to fix.

**Comment by LegalizeAdulthood** [comment]
Sorry, I didn't see your comment from Feb 21.  Given that your comment was 1 week after I filed the bug when I had the problem, the answer to your question is no, it didn't work.  That's why I filed the bug.

**Comment by Axel-Naumann** [comment]
Can you try the more traditional approach here: https://root.cern.ch/cling-build-instructions
Clone llvm and clang, both from root.cern.ch/git, then clone cling and off you go.

@bellenot can you confirm that the cling-on-Windows build works? How do you build usually?

**Comment by LegalizeAdulthood** [comment]
I did follow your web site instructions exactly the last time I tried this.  It takes many hours to compile all this stuff and I don't have the time to do that right now, sorry.

Why do you have your own git repo for clang/llvm?  Why aren't you using the llvm-mirror repositories on github?

Why aren't you using git submodules in order to coordinate which versions of which repos you are using?

**Comment by bellenot** [comment]
So here is what I did, after cloning the repos as described in [](https://root.cern.ch/cling-build-instructions):
```
C:\Users\bellenot\build\llvm\build>cmake -A x64 -Thost=x64 -DCMAKE_VERBOSE_MAKEFILE=ON ..\src
[...]
C:\Users\bellenot\build\llvm\build>cmake --build . --config Release -- /maxcpucount
```
And after 37 minutes, the build failed because of missing symbols in `tools\cling\tools\plugins\example\clingDemoPlugin`  and in `tools\clang\tools\c-index-test\c-index-test`, but `cling.exe` (and everything else) was successfully built.

Note that the command line is broken, it displays weird characters, I'll try to fix this asap

**Comment by bellenot** [comment]
And FYI, the issue with bad characters has been fixed in the current master

**Comment by Axel-Naumann** [comment]
@LegalizeAdulthood better now?

Thanks for the suggestion to use submodules - it has come up in the past, we never found it useful enough (we don't have a lot of people complaining about having to match the versions).

**Comment by LegalizeAdulthood** [comment]
It will be a while before I have time to come back to this.

**Comment by LegalizeAdulthood** [comment]
Possibly months until I can come back to it, if ever.

This is why I'm suggesting that you have prebuilt Windows binaries as releases.  I'm very familiar with the clang tree, having contributed many times to clang-tidy.  If **I** am having trouble building this, your average person will give up after 5 minutes of building, if they can even get that far.

This is why you need prebuilt binary releases.  Building this stuff is too complicated and takes WAY too long for 99.999% of the people that might be interested in trying this tool.

**Comment by ferdymercury** [comment]
Closing as the requested binaries is being tracked here https://github.com/root-project/cling/issues/337
