### ISSUE TITLE
cin can't get input in jupyter

### ISSUE THREAD

**Issue by LiAlbert** [root-project/cling#286]
![screenshot from 2019-03-03 10-35-33](https://user-images.githubusercontent.com/22775190/53690166-51ec1980-3da0-11e9-88a5-26373dc3431f.png)

**Comment by Axel-Naumann** [comment]
Interesting idea. The Python kernel implements this as a dedicated feature, try `print(input())`. So yes, this could be implemented in a C++ Python kernel, but I'd rather not do that in cling's Python kernel: it's meant to provide rudimentary functionality, showcasing how it can be used in the Jupyter context. Maybe Xeus would be a good candidate for this feature?
