### ISSUE TITLE
fix for gcc 8

### ISSUE THREAD

**Issue by jhgoebbert** [root-project/cling#289]
cling 0.5 is not building with gcc 8, because llvm 5.x does not build with gcc 8.

This would fix it
   https://bugzilla.redhat.com/show_bug.cgi?id=1540620
and I created a pull-request
   https://github.com/llvm/llvm-project/pull/11
but it is not that easy to get added to LLVM.

Perhaps you have a possibility to get this patch included to LLVM ... (?)

**Comment by Axel-Naumann** [comment]
You should be able to build just cling - `-DLLVM_BUILD_TOOLS=Off` should do. I'd rather upgrade our llvm - around the end of the year - than adding patches to our llvm.git. Are those two options reasonable for you? If all fails, people now have your patch!

**Comment by jhgoebbert** [comment]
-DLLVM_BUILD_TOOLS=Off is a good hint. I will try it.
Beside that, I am looking forward for the upgrade of your llvm. Thanks!
