### ISSUE TITLE
cling_2016-08-02_ubuntu16 complains about ABI mismatch, likely causes crashes.

### ISSUE THREAD

**Issue by catskul** [root-project/cling#29]
```
$ ./cling
Warning in cling::IncrementalParser::CheckABICompatibility():
  C++ ABI mismatch, compiled with __GLIBCXX__ v20160609 running with v20160413

****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
[cling]$ 

```

Seems like this conversation might be relevant, but might be out of date by now.

https://root.cern.ch/phpBB3/viewtopic.php?t=19882

**Comment by vgvassilev** [comment]
This message tells you that you have an ABI-incompatible setup. The binary you downloaded is compiled with libstdc++ `v20160609` and yours is older `v20160413`. Try building cling from source.

@karies could tell you more when he is back from vacation.

**Comment by catskul** [comment]
@vgvassilev is it more appropriate to log issues to https://github.com/vgvassilev/cling or here ? They seem to be the same code base, but github says they're not related.

**Comment by vgvassilev** [comment]
Yeah, my github repo appeared long before this one. This one is more frequently synced but if you file the issue there we will see it too.

**Comment by karies** [comment]
@catskul can you sudo apt update && sudo apt dist-upgrade? Looks like your gcc is out of date compared to what our builder node is using.

**Comment by catskul** [comment]
Is there a way for me to find out which version matches?

**Comment by karies** [comment]
You mean which ubuntu GCC package defines which libstdc++ version string? That seems to be generated at stamp time, i.e. it's tricky to find.

That said, I believe that only ROOT needs the __GLIBCXX__ check these days (because of the PCH); cling should be fine with the ABI check that it already has. I will move this check out of cling.

**Comment by SylvainCorlay** [comment]
I am having the same issue here.

**Comment by SylvainCorlay** [comment]
Although I am seeing that warning only when I try to execute things in a kernel, not with the interpreter.

**Comment by SylvainCorlay** [comment]
Actually, I am seeing the oposite error

runnin with v20160609
compiled with v20160413

**Comment by SylvainCorlay** [comment]
@vgvassilev @karies did you start building cling with v20160413 again for ubuntu 16?

**Comment by vgvassilev** [comment]
Where did you download the binary from?

**Comment by SylvainCorlay** [comment]
The file I got for the hacked binder recipe is https://root.cern.ch/download/cling/cling_2016-10-09_ubuntu16.tar.bz2

**Comment by Axel-Naumann** [comment]
Should be fixed in the HEAD of master.
