### ISSUE TITLE
undo works fine only for small & simple code snippets

### ISSUE THREAD

**Issue by blockspacer** [root-project/cling#299]
Is it planned to fix undo?

It may allow live coding in many C++ projects ( similar to https://www.youtube.com/watch?v=dY9CFugqXmo )

Unloading (needed for reloading) will be an awesome feature

example code:
+ https://root-forum.cern.ch/t/cling-reload-unload-doesnt-work/15797/5
+ https://root-forum.cern.ch/t/understanding-undo-and-interpreter-unload/20601/11

**Comment by Axel-Naumann** [comment]
See https://github.com/root-project/root/pull/4214 - it's coming!

**Comment by blockspacer** [comment]
> See [root-project/root#4214](https://github.com/root-project/root/pull/4214) - it's coming!

Thanks for response. That`s awesome news!
