### ISSUE TITLE
Error while performing operations on directory Mac OS

### ISSUE THREAD

**Issue by AInitikesh** [root-project/cling#314]
I ran 
cling -L /Users/xxxx/yyyyy/vcpkg/installed/x64-osx/lib/libboost_filesystem.a -I /Users/xxxx/yyyyy/vcpkg/installed/x64-osx/include/

and tried following code throws error

**[cling]$ #include <boost/filesystem.hpp>**
**[cling]$ boost::filesystem::path p = "HH";**
**[cling]$ for (auto i = boost::filesystem::directory_iterator(p); i != boost::filesystem::directory_iterator(); i++)**
IncrementalExecutor::executeFunction: symbol '_ZN5boost10filesystem6detail28directory_iterator_constructERNS0_18directory_iteratorERKNS0_4pathEPNS_6system10error_codeE' unresolved while linking [cling interface function]!
You are probably missing the definition of boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*)
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5boost10filesystem6detail13dir_itr_closeERPvS3_' unresolved while linking [cling interface function]!
You are probably missing the definition of boost::filesystem::detail::dir_itr_close(void*&, void*&)
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN5boost10filesystem6detail28directory_iterator_incrementERNS0_18directory_iteratorEPNS_6system10error_codeE' unresolved while linking [cling interface function]!
You are probably missing the definition of boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*)
Maybe you need to load the corresponding shared library?

same is the error with 
**#include <filesystem>**
**std::filesystem::create_directories("/Users/xxxx/yyyyy/sandbox/1/2/a");**

**Comment by ferdymercury** [comment]
Please retry with current master and reopen if it's still an issue.
