### ISSUE TITLE
Consider contributing the project to LLVM

### ISSUE THREAD

**Issue by bmanga** [root-project/cling#317]
Hi, I was wondering if there has been any thought about proposing to put the project under the LLVM umbrella, given the project's reliance on clang's and llvm's ever-changing apis. It would help keep the project in sync with upstream and potentially gain more visibility/contributors.

**Comment by marty1885** [comment]
Hi, is looking at having a incubator project so project can have more help if they want to be a sub project. For cling, this allows cling to keep up with clang and LLVM's changing APIs. Hope this helps.

Source: https://www.phoronix.com/scan.php?page=news_item&px=LLVM-Incubator-New-Projects

**Comment by vgvassilev** [comment]
Good points. We have been investing in that direction. See [here](https://reviews.llvm.org/D96033).

**Comment by bmanga** [comment]
That's amazing! Thanks for the work :D
