### ISSUE TITLE
Load, unload and load anonymous namespace will cause errors

### ISSUE THREAD

**Issue by LongyuYang** [root-project/cling#318]
@Axel-Naumann Load, unload and load anonymous namespace will generate an error:
```bash
.L test.h
.U test.h
.L test.h
```
The error info is:
```bash
error: use of undeclared identifier 'test'
  template<> class info<test<int> > {};
```
The content of `test.h` is:
```c++
#ifndef test_1
#define test_1
namespace {
  template<typename T> class test;
}

namespace hello{
  template<typename T> class info;
  template<> class info<test<int> > {};
}
#endif
```
If we omit the anonymous namespace specifier `namespace{}`, there will be no error:
```c++
#ifndef test_1
#define test_1
 template<typename T> class test;
namespace hello{
  template<typename T> class info;
  template<> class info<test<int> > {};
}
#endif
```

**Comment by ruiqi-gao** [comment]
I have encountered the same problem, It will be much appreciated if cling developing team could solve this problem

**Comment by ferdymercury** [comment]
The error is no longer present on current master, please reopen if it's still an issue
