### ISSUE TITLE
Fix problem with loading libraries that link against LLVM

### ISSUE THREAD

**Issue by deliciouslytyped** [root-project/cling#332]
@vgvassilev said in https://root-forum.cern.ch/t/how-to-load-an-shared-object-that-also-depends-on-clang-llvm-in-cling/38054/5 that this is something you will work towards fixing, so I thought I'd open an issue for it.

Related: https://github.com/root-project/cling/issues/201 https://github.com/symengine/symengine/issues/1473
There seems to be a case of doing the proper symbol hiding in https://github.com/conda-forge/llvmdev-feedstock/pull/65

I'd give a more verbose explanation but I'm not sure I understand the issue completely correctly.

**Comment by Axel-Naumann** [comment]
I'm confused - the conda discussion seems to be about ROOT while you have reported a cling bug here? Cling doesn't tell you how to build your llvm, are you saying that it should?

**Comment by Axel-Naumann** [comment]
Let me know whether I can provide any help here - right now I don't know how.

**Comment by isuruf** [comment]
You can link to LLVM, with `-Wl,--exclude-libs` on Linux (or similar on OSX) as in https://github.com/symengine/symengine/blob/master/symengine/CMakeLists.txt#L251-L258 when cling is linking to LLVM statically.
