### ISSUE TITLE
Error trying run simple script

### ISSUE THREAD

**Issue by andrey-str** [root-project/cling#333]
```c++
#!/usr/bin/env cling

#include <vector>
#include <iostream>

using namespace std;

std::vector<int> v = {1,2,3};

for(auto i: v)
{
    cout << i;
}
```

Running this in terminal results in the error:

```bash
input_line_8:3:10: error: use of undeclared identifier 'i'
        cout << i;
```

Interesting that if I run cling in interpreter mode, then the  very same code runs fine. I get 123 output as expected without error.

Also, what is C++ standard is being used by default?

Thanks in advance.

**Comment by vgvassilev** [comment]
Could you move the opening curly brace of the for-loop on the same line?

**Comment by andrey-str** [comment]
> Could you move the opening curly brace of the for-loop on the same line?

It worked. But why?

**Comment by Axel-Naumann** [comment]
cling is parsing your file line by line - if a line has no continuation it doesn't know that the statement is continuing on the next line. By providing a trailing `{` cling knows to expect more.

In general it might be simpler to wrap statements into a function and call that at the end.
