### ISSUE TITLE
could I use cling with OpenMP?

### ISSUE THREAD

**Issue by cxwx** [root-project/cling#345]
```
{
#pragma omp parallel for
for(int I = 0; I<10; I++)
{
cout<<i<<endl;
}
}
```

the result seems no OpenMPSupport

**Comment by SimeonEhrig** [comment]
Yes, you can. You have to start the cling with some additional arguments to enable the OpenMP mode: `cling -fopenmp -llibomp`

**Comment by cxwx** [comment]
thanks
