### ISSUE TITLE
Travis Error: fatal error: llvm/Config/config.h: No such file or directory

### ISSUE THREAD

**Issue by SimeonEhrig** [root-project/cling#349]
Travis throw the error `fatal error: llvm/Config/config.h: No such file or directory` at every build. For example see: https://travis-ci.org/github/root-project/cling/builds/699522924

The reason is, because `cpt` downloads an pre-compiled llvm version from https://releases.llvm.org/download.html#5.0.2. Unfortunately, this version doesn't contains the `config.h`. I think the reason for this is that `config.h` is build/system dependent and has no install target. A possible solution would be to use the llvm source code. But then it is possible that Travis gets a timeout.

**Comment by SimeonEhrig** [comment]
Commit 8b34a4c solves the problem.

@vgvassilev 
On my local system, when I build from source, I have the same `cling-test` `CodeGeneration/Lambda.C` error.

**Comment by Axel-Naumann** [comment]
`CodeGeneration/Lambda.C` is fixed.
