### ISSUE TITLE
Cling build seems to swap

### ISSUE THREAD

**Issue by strattist** [root-project/cling#350]
Hi guys, I don't know if some of you had this issue before but it seems on my system that the cling build done from this command is swapping like crazy:

`./cpt.py --create-dev-env Debug --with-workdir=./cling-build/` 

My last build messages are:

```
[ 95%] Linking CXX shared library ../../../../lib/libclang.so
[ 95%] Linking CXX shared library ../../../../lib/libclingJupyter.so
[ 95%] Linking CXX shared library ../../../../lib/libcling.so
[ 95%] Linking CXX executable ../../../../bin/cling-demo
```

Is there to reduce the number of core cling is using to build in order to reduce the allocated memory during the build?

My system: Linux Ubuntu 18.04, 16GB RAM, 4 physical cores, GCC 7.5.0

**Comment by reikdas** [comment]
> Is there to reduce the number of core cling is using to build in order to reduce the allocated memory during the build?

There is no such provision in cpt right now. 
@vgvassilev Maybe we should add a flag to specify the number of cores?

**Comment by Sologala** [comment]
Hi, @strattist. I met this problem yesterday. In my first thinking, i just want to reduce the make thread, and do this modify as follows:
### 1. reduce cores(threads)
input the number of threads at line `528` at  `cpt.py`: 
```shell
self.cores = 2
```
### 2. increase swap patition
but i still not deal the build crash. After search in internet, i found that error is cause by the less of memory, so i just increase the swap partition by creating new swap file.
```shell
sudo dd if=/dev/zero of=swapfile bs=1G count=16 
sudo chmod 600 swapfile
sudo mkswap swapfile
sudo swapon swapfile
```

By doing that , I successfully builded cling in my almost broken tiny laptop. Hope this will help you.

this method just uses the new swapfile in your cur path for once. the new swap partition will dismiss automaticly when you reboot your computer . To save the disk space , you can delete the swapfile.

**Comment by vgvassilev** [comment]
What about adding `-DLLVM_PARALLEL_LINK_JOBS=2` via the extra cmake options flag?

**Comment by Axel-Naumann** [comment]
Clarified, I guess...
