### ISSUE TITLE
Compilation error : "'isComputedNoexcept': identifier not found "

### ISSUE THREAD

**Issue by elix22** [root-project/cling#357]
I followed the build instructions on the Github page.
This is a Windows build , but I got them same error on my Mac .

1 - wget https://raw.githubusercontent.com/root-project/cling/master/tools/packaging/cpt.py
2 - python cpt.py --create-dev-env Release --with-workdir=./cling-build/

The full error : 
**D:\Cling-2\cling-build\cling-src\tools\cling\lib\Interpreter\ForwardDeclPrinter.cpp(493,13): error C3861: 'isComputedNoexcept': identifier not found [D:\Cling-2\cling-build\builddir\tools\cling\lib\Interpreter\obj.clingInterpreter.vcxproj
]**

**Comment by elix22** [comment]
@Axel-Naumann 
I noticed that you made this change , which is causing compilation error  (at least for me).
https://github.com/root-project/cling/commit/4203690c46e438f6e43f1aaf8cb41b8b582c6002

Please advice . 
Thanks.

**Comment by Islam0mar** [comment]
The downloaded clang is an older version:
`tools/clang/include/clang/Basic/ExceptionSpecificationType.h` doesn't define  `isComputedNoexcept'`
I modified `ForwardDeclPrinter.cpp(493)` to use `FT->getExceptionSpecType() == EST_ComputedNoexcept` and it works.

**Comment by elix22** [comment]
Right , I did the same thing 
Reverted back commit https://github.com/root-project/cling/commit/4203690c46e438f6e43f1aaf8cb41b8b582c6002
Thanks

**Comment by Axel-Naumann** [comment]
I will update your clang branch to contain the backported commits. I will let you know once done.

**Comment by Axel-Naumann** [comment]
Should be fixed, could someone confirm, please?

**Comment by reikdas** [comment]
Works for me :) Thanks!

**Comment by SimeonEhrig** [comment]
I can also confirm, that it works.
For the others the backport was made in the clang branch. So please update your clang project.
