### ISSUE TITLE
On the enabling and disabling the allowing of redefinitions

### ISSUE THREAD

**Issue by SylvainCorlay** [root-project/cling#360]
It appears to be possible to enable / disable the allowing of redefinition with the following

```cpp
#include "cling/Interpreter/Interpreter.h"
cling::runtime::gCling->allowRedefinition(false);  // disabling
cling::runtime::gCling->allowRedefinition();       // enabling
```

However the `cling/Interpreter/Interpreter.h` headers includes LLVM headers while llvm-dev is not a runtime requirement of cling. This matters when packaging cling for e.g. conda because we try to keep runtime dependencies minimal.

- Would it be possible (or would you accept a PR) to make provide these apis in a way that does not require llvm-dev at runtime?

**Comment by Axel-Naumann** [comment]
@jalopezg-uc3m @pcanal what do you think? Some new dot-command maybe?

**Comment by SylvainCorlay** [comment]
at the momwnt we are not supporting dot commands yet in xeus-cling (but will as soon as I  have a couple of days to look at it). a c++ api would be perfect!

**Comment by pcanal** [comment]
Maybe we should have a lighter weight header:
```
/// Interpreter configuration
namespace cling {
namespace config {
bool AllowRedefinition(bool); 
etc ...
}}
```

**Comment by jalopezg-uc3m** [comment]
> Maybe we should have a lighter weight header:
> 
> ```
> /// Interpreter configuration
> namespace cling {
> namespace config {
> bool AllowRedefinition(bool); 
> etc ...
> }}
> ```

Indeed.  We might offer a separate interface for configuring these aspects.  I took this week off; I will take care of this as soon as I am back.  :-)

**Comment by SylvainCorlay** [comment]
Awesome!

**Comment by SylvainCorlay** [comment]
Hey @jalopezg-r00t is this something you got to look at?

**Comment by jalopezg-r00t** [comment]
Thanks for pinging!  Sorry, I was working on different stuff.  I will work on this in the next days.  :-)

**Comment by jalopezg-r00t** [comment]
Fix already in `master` branch.  Closing.
