### ISSUE TITLE
Embedding Cling in iOS app

### ISSUE THREAD

**Issue by serjepatoff** [root-project/cling#361]
Is it possible to embed cling on platforms where JIT (VM_PROT_WRITE+VM_PROT_EXECUTE pages manipulation) is explicitly forbidden? Like iOS?

I want to make C++ tutor+playground app for students working on iPad.

I.e. can Cling interpret LLVM bitcode directly, without JITing, in the grassroot sense of the word “interpretation”? Of course it will be slow, but for edu and experiment purposes it is ok.

**Comment by Axel-Naumann** [comment]
We are only pursuing JIT compilation, not interpretation. To my knowledge what you want would need quite some development work... OTOH some interpreters available on iOS also generate binary code IIUC, so maybe there's a way?

**Comment by Axel-Naumann** [comment]
And let me know once it's okay to close this issue!

**Comment by serjepatoff** [comment]
There are 2 kinds of in-app compilation available on iOS. 

1. Indirect bytecode emitting that will be interpreted by machine code.

2. Usage of system-wide JavaScriptCore.

In-app emitting of machine code, either ahead of time or just in time is prohibited by using simple technique: memory sections with execution bit set are not available for write, and sections with write bit set are not available for execution.

I’ve heard iOS 14 may provide relaxed rules, need to check it.

Close this issue as irrelevant. And thank you for answer!

**Comment by vgvassilev** [comment]
Thank you!
