### ISSUE TITLE
cpt.py seems to check out the wrong Clang revision

### ISSUE THREAD

**Issue by thomasjm** [root-project/cling#368]
I'm trying to build Cling 0.7 by calling `cpt.py` like this: `./cpt.py --last-stable tar`.

I notice it is choosing the `llvm_revision` to be `release_50`, and then it's checking out the corresponding Clang revision on this line:

https://github.com/root-project/cling/blob/70163975eee5a76b45a1ca4016bfafebc9b57e07/tools/packaging/cpt.py#L352

As a result, it tries to check out the Clang tag `cling-patches-rrelease_50`. 

However, this doesn't build successfully. For one thing, Clang seems to be missing [this commit](https://root.cern/gitweb/?p=clang.git;a=commit;h=02c41d5edd15232b0b25ec1d842403552c2aceb4) which causes the build to fail as on https://github.com/root-project/cling/issues/294.

At this point I compared `cling-patches-rrelease_50` to `cling-patches` and noticed that
* `cling-patches` has about 6 more commits, one of which is the one I needed to fix the build
* One of those extra commits also has the tag `cling-v0.7`, which makes me think I should be using that one.

So, it seems `cpt.py` is misbehaving and it needs to choose the `cling-v0.7` tag when trying to build version 0.7. Or, `cling-patches-rrelease_50` needs the extra commits cherry-picked into it?

**Comment by reikdas** [comment]
Can you checkout the latest master and try again?

**Comment by thomasjm** [comment]
I actually ended up giving up on `cpt.py` and reconstructing the subset of it that I needed -- you can feel free to close this issue as far as I'm concerned.
