### ISSUE TITLE
CI fails since redifintion interface update

### ISSUE THREAD

**Issue by SimeonEhrig** [root-project/cling#373]
Since commit 904796d2bbf9dc08413dd188ff618a34d55d8d31 which changes the interface to enable redefinition, the `test/CodeUnloading/DeclShadowing.C` test failes.

@jalopezg-r00t Can you please fix this.

**Comment by jalopezg-r00t** [comment]
Sorry!  Thanks for reporting, @SimeonEhrig.  Fixed in commit c054ac284042aadbe6c4cb40842a3c3d6923d8d8.

Cheers,
J.
