### ISSUE TITLE
Prebuilt binary on OpenSuse

### ISSUE THREAD

**Issue by mulderp** [root-project/cling#376]
Hello,
I am trying to run the pre-built cling package from https://root.cern/download/cling/

On my OpenSuse machine I get:

```
pmu@linux-lykr:~/projects/cpp/cling/prebuild/cling_2020-11-05_ROOT-fedora32> bin/cling 
bin/cling: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by bin/cling)
bin/cling: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by bin/cling)
``` 

Do you have a pointer how to run this package (the custom build is one option but it is running for 1h already without any progress output from cpt.py )

Thanks!

**Comment by mulderp** [comment]
someone pointed me to follow the install strategy pointed out here: https://iscinumpy.gitlab.io/post/root-conda/

**Comment by mulderp** [comment]
Also here is the current glibc info from my shell:

```
 zypper info glibc 
Loading repository data...
Reading installed packages...


Information for package glibc:
------------------------------
Repository     : openSUSE-Leap-15.2-1
Name           : glibc
Version        : 2.26-lp152.25.10
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 6.7 MiB
Installed      : Yes
Status         : up-to-date
Source package : glibc-2.26-lp152.25.10.src
Summary        : Standard Shared Libraries (from the GNU C Library)
Description    : 
    The GNU C Library provides the most important standard libraries used
    by nearly all programs: the standard C library, the standard math
    library, and the POSIX thread library. A system is not functional
    without these libraries.


```

**Comment by mulderp** [comment]
It seems a newer glibc version will be added in OpenSuse Leap 15.3 https://en.opensuse.org/Portal:15.3

**Comment by SylvainCorlay** [comment]
@mulderp note that you can use the conda package for cling on most linux distributions.

**Comment by mulderp** [comment]
Thanks - Indeed conda install seems to work quite well for OpenSuse too.
Now trying to install Cling-xeus combo:

```
(base) pmu@linux-lykr:~/projects/cpp/cling>  conda install -c conda-forge xeus-cling 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment:  (waiting for 10-20min)
```

**Comment by SylvainCorlay** [comment]
@mulderp I recomment not using the full anaconda install, but e.g. miniconda, or even (much) better miniforge (https://github.com/conda-forge/miniforge) which is maintained by the conda-forge community, and available on many more platforms. Miniforge is much smaller than anaconda and is really open-source.

Also, miniforge defaults to conda-forge, so no need to specify `-c conda-forge`.

If you use the `mambaforge` flavor, you will get mamba in the base env, which is a drop-in replacement to the conda command-line utility and is 100x faster.

**Comment by mulderp** [comment]
Thanks, this works nicely:
 
   1) Download Miniconda Installer from: https://docs.conda.io/en/latest/miniconda.html
   2) $ sh Miniconda3-latest-Linux-x86_64.sh  # wait 5 mins and reload environment
   3) Install cling and xeus:

      conda create -n cling
      conda activate cling  # Or `source activate cling` for conda < 4.6

      conda install xeus-cling -c conda-forge

**Comment by SylvainCorlay** [comment]
Hi @mulderp I don't recommend using miniconda over miniforge, because this typically leads to mixing anaconda and conda-forge channels. 

1. Download mambaforge for your platform at https://github.com/conda-forge/miniforge#mambaforge
2. Install mambaforge
3. `mamba install xeus-cling`

No need to specify `-c conda-forge` and this is guaranteed to get everything from conda-forge. The anaconda channel is not quite fully compatible with conda-forge, and it is not getting better.

**Comment by mulderp** [comment]
Thanks, I agree, the mamba user experience feels good.
I was able to install Jupyterlab but when trying 

   mamba install xeus-cling

I get:

    Problem: nothing provides requested xeus-cling

**Comment by SylvainCorlay** [comment]
@mulderp specifying conda-forge is still requires when starting from miniconda. I recommend starting from miniforge or mambaforge to prevent mixing channels.
