### ISSUE TITLE
cling 0.8 release build issue

### ISSUE THREAD

**Issue by chenrui333** [root-project/cling#379]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build failure</summary>

```
[ 97%] Building CXX object tools/clang/lib/StaticAnalyzer/Checkers/CMakeFiles/clangStaticAnalyzerCheckers.dir/NSAutoreleasePoolChecker.cpp.o
cd /tmp/cling-20210113-57930-1l2e8hd/build/tools/clang/lib/StaticAnalyzer/Checkers && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DGTEST_HAS_RTTI=0 -DLLVM_BUILD_GLOBAL_ISEL -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/cling-20210113-57930-1l2e8hd/build/tools/clang/lib/StaticAnalyzer/Checkers -I/tmp/cling-20210113-57930-1l2e8hd/src/tools/clang/lib/StaticAnalyzer/Checkers -I/tmp/cling-20210113-57930-1l2e8hd/src/tools/clang/include -I/tmp/cling-20210113-57930-1l2e8hd/build/tools/clang/include -I/tmp/cling-20210113-57930-1l2e8hd/build/include -I/tmp/cling-20210113-57930-1l2e8hd/src/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fno-common -Woverloaded-virtual -Wno-nested-anon-types -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk  -fno-exceptions -fno-rtti -o CMakeFiles/clangStaticAnalyzerCheckers.dir/NSAutoreleasePoolChecker.cpp.o -c /tmp/cling-20210113-57930-1l2e8hd/src/tools/clang/lib/StaticAnalyzer/Checkers/NSAutoreleasePoolChecker.cpp
/tmp/cling-20210113-57930-1l2e8hd/src/tools/cling/lib/Interpreter/ForwardDeclPrinter.cpp:493:13: error: use of undeclared identifier 'isComputedNoexcept'
        if (isComputedNoexcept(FT->getExceptionSpecType())) {
            ^
1 error generated.
make[2]: *** [tools/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/ForwardDeclPrinter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

</details>

Full build log is in here, https://github.com/Homebrew/homebrew-core/runs/1695928596
relates to https://github.com/Homebrew/homebrew-core/pull/68925

**Comment by SimeonEhrig** [comment]
Did you pulled the latest commits on the `cling-patches` branch in the clang repository? In the past, I had the same error and it was fixed.

**Comment by chenrui333** [comment]
nope, let me check on it.

**Comment by chenrui333** [comment]
@SimeonEhrig what patch tag should I use for clang and llvm?

**Comment by chenrui333** [comment]
for clang, here are the release tags I saw

```
$ git tag -l | grep cling-patches
cling-patches-is-missing-making-all-static-init
cling-patches-minimal-rebase-pre-FIXUP
cling-patches-r191429
cling-patches-r199798
cling-patches-r201395
cling-patches-r202469
cling-patches-r210169
cling-patches-r214395
cling-patches-r214630
cling-patches-r214630-old
cling-patches-r225983
cling-patches-r226163
cling-patches-r227305
cling-patches-r227800
cling-patches-r272382
cling-patches-r274612
cling-patches-r302975
cling-patches-rrelease_50
```


for llvm:

```
$ git tag -l | grep cling-patches
cling-patches-r191429
cling-patches-r201395
cling-patches-r202469
cling-patches-r210169
cling-patches-r214395
cling-patches-r214630
cling-patches-r226163
cling-patches-r227800
cling-patches-r272382
cling-patches-r274612
cling-patches-r302975
cling-patches-rrelease_50
```

**Comment by chenrui333** [comment]
have seen `r302975` in one of the previous PRs, https://github.com/Homebrew/homebrew-core/pull/47309

**Comment by chenrui333** [comment]
ping @SimeonEhrig

**Comment by SimeonEhrig** [comment]
@chenrui333 
Sorry for the late reply. I was busy over the weekend. Sorry as well, I made a mistake. The name of the branch is `cling-patches`.
The current commit hashes are:
- llvm: 9c749361ba8c2d400b83d8cc5c544287465b7489
- clang: 7a13d39940cfd2bd1f486cb8b70a4ce09c076222

With the current `cling-patches` branches, I can successful build the current master.

To be sure, you can check out the `cling-v0.8` tag in the clang branch. For the llvm branch, the tag is missing at the moment (see #380 ).

**Comment by chenrui333** [comment]
yeah, I noticed the tags were missing for llvm (it was built fine with `cling-0.7`, so I did not report that issue :) ).

**Comment by chenrui333** [comment]
@SimeonEhrig do mind tagging those two commits (I could not do the branch checkout on the homebrew side)

**Comment by SimeonEhrig** [comment]
> @SimeonEhrig do mind tagging those two commits in the two repos (I could not do the branch checkout on the homebrew side)

Technically not, because nothing has changed in llvm repo since version 0.6. But for manuals and scripts it is better to have the same tags to not confuse other people and my future self.

**Comment by razzius** [comment]
I was able to get v0.9 merged into homebrew: https://github.com/Homebrew/homebrew-core/pull/76750#issuecomment-834883050

Perhaps this can be closed?

**Comment by ferdymercury** [comment]
Please reopen if it still fails with latest master
