### ISSUE TITLE
error: no member named 'addOverlay' in 'clang::CompilerInvocation'

### ISSUE THREAD

**Issue by yurivict** [root-project/cling#383]
cling-0.8 fails with llvm-10:
```
/usr/ports/lang/cling/work/cling-0.8/lib/Interpreter/CIFactory.cpp:724:26: error: no member named 'addOverlay' in 'clang::CompilerInvocation'
      CI.getInvocation().addOverlay(FS);
      ~~~~~~~~~~~~~~~~~~ ^
1 error generated.
```
Same error with the oldest available llvm-6,

LastKnownGoodLLVMSVNRevision.txt says that last llvm version is 50 which is EOLed.

**Comment by SimeonEhrig** [comment]
You need to use the Clang and LLVM fork from Root, because they include patches for Cling: https://root.cern/cling/cling_build_instructions/
