### ISSUE TITLE
Variable template instantiation does not create static constexpr member

### ISSUE THREAD

**Issue by Eximius** [root-project/cling#384]
This breaks ROOT::RDataFrame, among other things.

In RDataFrame's case TypeTraits<ArgTypes>::list_size does not exist.

Even though  the static member exists in `TypeTraits.hxx`:
```cpp
namespace ROOT {

/// ROOT type_traits extensions
namespace TypeTraits {
/// Lightweight storage for a collection of types.
/// Differently from std::tuple, no instantiation of objects of stored types is performed
template <typename... Types>
struct TypeList {
   static constexpr std::size_t list_size = sizeof...(Types);
};
} // end ns TypeTraits
```

Reproduce with:
```cpp
ROOT::RDataFrame d(50);
int i = 0;
d.Define("test", [&i]() { return (double)i; }).Filter("test > 10");
```

Or  with: 
```cpp
ROOT::RDataFrame d(50);
int i = 0;
d.Define("test", [&i]() { return (double)i; });
d.Filter([](double test){ return test > 0;}, {"test"});
```

Exists both on latest swan 
![image](https://user-images.githubusercontent.com/565049/106065386-85a25c00-60fb-11eb-8d0a-ab428f0dc4dc.png)

and local archlinux:
```
Name            : root
Version         : 6.22.06-2
```

**Comment by Eximius** [comment]
It needed 
```
#include "TROOT.h"
```
in the macro .C file for some reason. Confusing. Never written in the reference docs seemingly.

**Comment by Mallchad** [comment]
@Eximius please marked this issue as resolved if you've fixed your problem

**Comment by ferdymercury** [comment]
Seems to work with latest master, please reopen if you reproduce the failure, thanks.
