### ISSUE TITLE
CI failes because of svn export error in cpt.py

### ISSUE THREAD

**Issue by SimeonEhrig** [root-project/cling#385]
The current CI jobs fails, because the command `svn export http://llvm.org/svn/llvm-project/llvm/branches/release_50/utils/FileCheck FileCheck` in the `cpt.py` script fails: https://github.com/root-project/cling/runs/1681513196 

I think, this happens, because the llvm project moved from svn to git and at some point, they deactivate the svn repository.

**Comment by SimeonEhrig** [comment]
ping @reikdas

**Comment by reikdas** [comment]
Fixed in master.
