### ISSUE TITLE
Upgrading LLVM and Clang repo for LLVM 9

### ISSUE THREAD

**Issue by SimeonEhrig** [root-project/cling#388]
@Axel-Naumann @vgvassilev Congratulation for merging the LLVM 9 upgrade. But I believe you forgot to upgrade the official root Clang and LLVM repo.

* http://root.cern/git/clang.git
* http://root.cern/git/llvm.git

Can you please do this. 

In the meantime, if someone tries to build the current cling version, she or he should use Vassil's froks.

* https://github.com/vgvassilev/clang/tree/upgrade_llvm90
* https://github.com/vgvassilev/llvm/tree/upgrade_llvm90

**Comment by Axel-Naumann** [comment]
That's a known glitch - @vgvassilev will update these repos!

**Comment by vgvassilev** [comment]
@SimeonEhrig, thanks for pinging. Can you retry now?

**Comment by SimeonEhrig** [comment]
@vgvassilev I works. Thanks for fixing it.
