### ISSUE TITLE
Compilation error on debian buster 64bit

### ISSUE THREAD

**Issue by fslurrehman** [root-project/cling#408]
Hi, 
I was compiling and got the error near completion of compilation. Is there any way to compile this correctly:

`In file included from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalExecutor.h:13,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalExecutor.cpp:10:
/home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h: In constructor ‘cling::IncrementalJIT::RemovableObjectLinkingLayer::RemovableObjectLinkingLayer(cling::IncrementalJIT::SymbolMapT&, llvm::orc::ExecutionSession&, llvm::orc::LegacyRTDyldObjectLinkingLayer::ResourcesGetter, cling::IncrementalJIT::NotifyObjectLoadedT, cling::IncrementalJIT::RemovableObjectLinkingLayer::NotifyFinalizedFtor)’:
/home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h:106:74: warning: ‘llvm::orc::LegacyRTDyldObjectLinkingLayer::LegacyRTDyldObjectLinkingLayer(llvm::orc::ExecutionSession&, llvm::orc::LegacyRTDyldObjectLinkingLayer::ResourcesGetter, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyLoadedFtor, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyFinalizedFtor, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyFreedFtor)’ is deprecated [-Wdeprecated-declarations]
       : Base_t(ES, RG, NotifyLoaded, NotifyFinalized), m_SymbolMap(SymMap)
                                                                          ^
In file included from /home/faisal/software/cling-build/cling-src/include/llvm/Support/AlignOf.h:16,
                 from /home/faisal/software/cling-build/cling-src/include/llvm/ADT/SmallVector.h:17,
                 from /home/faisal/software/cling-build/cling-src/include/llvm/ADT/SmallString.h:16,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/include/cling/Utils/Output.h:13,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h:13,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalExecutor.h:13,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalExecutor.cpp:10:
/home/faisal/software/cling-build/cling-src/include/llvm/ExecutionEngine/Orc/RTDyldObjectLinkingLayer.h:357:7: note: declared here
       LegacyRTDyldObjectLinkingLayer(
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/faisal/software/cling-build/cling-src/include/llvm/Support/Compiler.h:280:3: note: in definition of macro ‘LLVM_ATTRIBUTE_DEPRECATED’
   decl __attribute__((deprecated))
   ^~~~
In file included from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.cpp:10:
/home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h: In constructor ‘cling::IncrementalJIT::RemovableObjectLinkingLayer::RemovableObjectLinkingLayer(cling::IncrementalJIT::SymbolMapT&, llvm::orc::ExecutionSession&, llvm::orc::LegacyRTDyldObjectLinkingLayer::ResourcesGetter, cling::IncrementalJIT::NotifyObjectLoadedT, cling::IncrementalJIT::RemovableObjectLinkingLayer::NotifyFinalizedFtor)’:
/home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h:106:74: warning: ‘llvm::orc::LegacyRTDyldObjectLinkingLayer::LegacyRTDyldObjectLinkingLayer(llvm::orc::ExecutionSession&, llvm::orc::LegacyRTDyldObjectLinkingLayer::ResourcesGetter, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyLoadedFtor, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyFinalizedFtor, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyFreedFtor)’ is deprecated [-Wdeprecated-declarations]
       : Base_t(ES, RG, NotifyLoaded, NotifyFinalized), m_SymbolMap(SymMap)
                                                                          ^
In file included from /home/faisal/software/cling-build/cling-src/include/llvm/Support/AlignOf.h:16,
                 from /home/faisal/software/cling-build/cling-src/include/llvm/ADT/SmallVector.h:17,
                 from /home/faisal/software/cling-build/cling-src/include/llvm/ADT/SmallString.h:16,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/include/cling/Utils/Output.h:13,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h:13,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.cpp:10:
/home/faisal/software/cling-build/cling-src/include/llvm/ExecutionEngine/Orc/RTDyldObjectLinkingLayer.h:357:7: note: declared here
       LegacyRTDyldObjectLinkingLayer(
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/faisal/software/cling-build/cling-src/include/llvm/Support/Compiler.h:280:3: note: in definition of macro ‘LLVM_ATTRIBUTE_DEPRECATED’
   decl __attribute__((deprecated))
   ^~~~
[100%] Building CXX object tools/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/IncrementalParser.cpp.o
/home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.cpp: In constructor ‘cling::IncrementalJIT::IncrementalJIT(cling::IncrementalExecutor&, std::unique_ptr<llvm::TargetMachine>, llvm::orc::LegacyIRCompileLayer<cling::IncrementalJIT::RemovableObjectLinkingLayer, llvm::orc::SimpleCompiler>::NotifyCompiledCallback)’:
/home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.cpp:356:33: warning: ‘llvm::orc::LegacyIRCompileLayer<BaseLayerT, CompileFtor>::LegacyIRCompileLayer(BaseLayerT&, CompileFtor, llvm::orc::LegacyIRCompileLayer<BaseLayerT, CompileFtor>::NotifyCompiledCallback) [with BaseLayerT = cling::IncrementalJIT::RemovableObjectLinkingLayer; CompileFtor = llvm::orc::SimpleCompiler; llvm::orc::LegacyIRCompileLayer<BaseLayerT, CompileFtor>::NotifyCompiledCallback = std::function<void(long unsigned int, std::unique_ptr<llvm::Module>)>]’ is deprecated [-Wdeprecated-declarations]
   m_LazyEmitLayer(m_CompileLayer) {
                                 ^
In file included from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h:20,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.cpp:10:
/home/faisal/software/cling-build/cling-src/include/llvm/ExecutionEngine/Orc/IRCompileLayer.h:136:1: note: declared here
 LegacyIRCompileLayer<BaseLayerT, CompileFtor>::LegacyIRCompileLayer(
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.cpp:356:33: warning: ‘llvm::orc::LazyEmittingLayer<BaseLayerT>::LazyEmittingLayer(BaseLayerT&) [with BaseLayerT = llvm::orc::LegacyIRCompileLayer<cling::IncrementalJIT::RemovableObjectLinkingLayer, llvm::orc::SimpleCompiler>]’ is deprecated [-Wdeprecated-declarations]
   m_LazyEmitLayer(m_CompileLayer) {
                                 ^
In file included from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h:21,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.cpp:10:
/home/faisal/software/cling-build/cling-src/include/llvm/ExecutionEngine/Orc/LazyEmittingLayer.h:265:1: note: declared here
 LazyEmittingLayer<BaseLayerT>::LazyEmittingLayer(BaseLayerT &BaseLayer)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-unused-local-typedef’
cc1plus: warning: unrecognized command line option ‘-Wno-covered-switch-default’
cc1plus: warning: unrecognized command line option ‘-Wno-nested-anon-types’
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-unused-local-typedef’
cc1plus: warning: unrecognized command line option ‘-Wno-covered-switch-default’
cc1plus: warning: unrecognized command line option ‘-Wno-nested-anon-types’
[100%] Building CXX object tools/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/Interpreter.cpp.o
[100%] Building CXX object tools/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/InterpreterCallbacks.cpp.o
In file included from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalExecutor.h:13,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalParser.cpp:22:
/home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h: In constructor ‘cling::IncrementalJIT::RemovableObjectLinkingLayer::RemovableObjectLinkingLayer(cling::IncrementalJIT::SymbolMapT&, llvm::orc::ExecutionSession&, llvm::orc::LegacyRTDyldObjectLinkingLayer::ResourcesGetter, cling::IncrementalJIT::NotifyObjectLoadedT, cling::IncrementalJIT::RemovableObjectLinkingLayer::NotifyFinalizedFtor)’:
/home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h:106:74: warning: ‘llvm::orc::LegacyRTDyldObjectLinkingLayer::LegacyRTDyldObjectLinkingLayer(llvm::orc::ExecutionSession&, llvm::orc::LegacyRTDyldObjectLinkingLayer::ResourcesGetter, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyLoadedFtor, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyFinalizedFtor, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyFreedFtor)’ is deprecated [-Wdeprecated-declarations]
       : Base_t(ES, RG, NotifyLoaded, NotifyFinalized), m_SymbolMap(SymMap)
                                                                          ^
In file included from /home/faisal/software/cling-build/cling-src/include/llvm/Support/Casting.h:17,
                 from /home/faisal/software/cling-build/cling-src/tools/clang/include/clang/Basic/LLVM.h:21,
                 from /home/faisal/software/cling-build/cling-src/tools/clang/include/clang/Basic/SourceLocation.h:17,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalParser.h:13,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalParser.cpp:10:
/home/faisal/software/cling-build/cling-src/include/llvm/ExecutionEngine/Orc/RTDyldObjectLinkingLayer.h:357:7: note: declared here
       LegacyRTDyldObjectLinkingLayer(
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[100%] Building CXX object tools/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/InvocationOptions.cpp.o
[100%] Building CXX object tools/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/LookupHelper.cpp.o
In file included from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalExecutor.h:13,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/Interpreter.cpp:21:
/home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h: In constructor ‘cling::IncrementalJIT::RemovableObjectLinkingLayer::RemovableObjectLinkingLayer(cling::IncrementalJIT::SymbolMapT&, llvm::orc::ExecutionSession&, llvm::orc::LegacyRTDyldObjectLinkingLayer::ResourcesGetter, cling::IncrementalJIT::NotifyObjectLoadedT, cling::IncrementalJIT::RemovableObjectLinkingLayer::NotifyFinalizedFtor)’:
/home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h:106:74: warning: ‘llvm::orc::LegacyRTDyldObjectLinkingLayer::LegacyRTDyldObjectLinkingLayer(llvm::orc::ExecutionSession&, llvm::orc::LegacyRTDyldObjectLinkingLayer::ResourcesGetter, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyLoadedFtor, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyFinalizedFtor, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyFreedFtor)’ is deprecated [-Wdeprecated-declarations]
       : Base_t(ES, RG, NotifyLoaded, NotifyFinalized), m_SymbolMap(SymMap)
                                                                          ^
In file included from /home/faisal/software/cling-build/cling-src/include/llvm/ADT/Optional.h:19,
                 from /home/faisal/software/cling-build/cling-src/include/llvm/ADT/STLExtras.h:19,
                 from /home/faisal/software/cling-build/cling-src/include/llvm/ADT/StringRef.h:12,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/include/cling/Interpreter/Interpreter.h:16,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/Interpreter.cpp:10:
/home/faisal/software/cling-build/cling-src/include/llvm/ExecutionEngine/Orc/RTDyldObjectLinkingLayer.h:357:7: note: declared here
       LegacyRTDyldObjectLinkingLayer(
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/faisal/software/cling-build/cling-src/include/llvm/Support/Compiler.h:280:3: note: in definition of macro ‘LLVM_ATTRIBUTE_DEPRECATED’
   decl __attribute__((deprecated))
   ^~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-unused-local-typedef’
cc1plus: warning: unrecognized command line option ‘-Wno-covered-switch-default’
cc1plus: warning: unrecognized command line option ‘-Wno-nested-anon-types’
[100%] Building CXX object tools/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/NullDerefProtectionTransformer.cpp.o                                                                                                                           
[100%] Building CXX object tools/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/RequiredSymbols.cpp.o
[100%] Building CXX object tools/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/Transaction.cpp.o
[100%] Building CXX object tools/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/TransactionUnloader.cpp.o
In file included from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalExecutor.h:13,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/Transaction.cpp:13:
/home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h: In constructor ‘cling::IncrementalJIT::RemovableObjectLinkingLayer::RemovableObjectLinkingLayer(cling::IncrementalJIT::SymbolMapT&, llvm::orc::ExecutionSession&, llvm::orc::LegacyRTDyldObjectLinkingLayer::ResourcesGetter, cling::IncrementalJIT::NotifyObjectLoadedT, cling::IncrementalJIT::RemovableObjectLinkingLayer::NotifyFinalizedFtor)’:
/home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h:106:74: warning: ‘llvm::orc::LegacyRTDyldObjectLinkingLayer::LegacyRTDyldObjectLinkingLayer(llvm::orc::ExecutionSession&, llvm::orc::LegacyRTDyldObjectLinkingLayer::ResourcesGetter, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyLoadedFtor, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyFinalizedFtor, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyFreedFtor)’ is deprecated [-Wdeprecated-declarations]
       : Base_t(ES, RG, NotifyLoaded, NotifyFinalized), m_SymbolMap(SymMap)
                                                                          ^
In file included from /home/faisal/software/cling-build/cling-src/include/llvm/Support/AlignOf.h:16,
                 from /home/faisal/software/cling-build/cling-src/include/llvm/Support/TrailingObjects.h:49,
                 from /home/faisal/software/cling-build/cling-src/tools/clang/include/clang/AST/DeclGroup.h:16,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/include/cling/Interpreter/Transaction.h:15,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/Transaction.cpp:10:
/home/faisal/software/cling-build/cling-src/include/llvm/ExecutionEngine/Orc/RTDyldObjectLinkingLayer.h:357:7: note: declared here
       LegacyRTDyldObjectLinkingLayer(
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalExecutor.h:13,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/TransactionUnloader.cpp:12:
/home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h: In constructor ‘cling::IncrementalJIT::RemovableObjectLinkingLayer::RemovableObjectLinkingLayer(cling::IncrementalJIT::SymbolMapT&, llvm::orc::ExecutionSession&, llvm::orc::LegacyRTDyldObjectLinkingLayer::ResourcesGetter, cling::IncrementalJIT::NotifyObjectLoadedT, cling::IncrementalJIT::RemovableObjectLinkingLayer::NotifyFinalizedFtor)’:
/home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h:106:74: warning: ‘llvm::orc::LegacyRTDyldObjectLinkingLayer::LegacyRTDyldObjectLinkingLayer(llvm::orc::ExecutionSession&, llvm::orc::LegacyRTDyldObjectLinkingLayer::ResourcesGetter, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyLoadedFtor, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyFinalizedFtor, llvm::orc::LegacyRTDyldObjectLinkingLayer::NotifyFreedFtor)’ is deprecated [-Wdeprecated-declarations]
       : Base_t(ES, RG, NotifyLoaded, NotifyFinalized), m_SymbolMap(SymMap)
                                                                          ^
In file included from /home/faisal/software/cling-build/cling-src/include/llvm/Support/AlignOf.h:16,
                 from /home/faisal/software/cling-build/cling-src/include/llvm/ADT/SmallVector.h:17,
                 from /home/faisal/software/cling-build/cling-src/include/llvm/ADT/SmallString.h:16,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/include/cling/Utils/Output.h:13,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalJIT.h:13,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/IncrementalExecutor.h:13,
                 from /home/faisal/software/cling-build/cling-src/tools/cling/lib/Interpreter/TransactionUnloader.cpp:12:
/home/faisal/software/cling-build/cling-src/include/llvm/ExecutionEngine/Orc/RTDyldObjectLinkingLayer.h:357:7: note: declared here
       LegacyRTDyldObjectLinkingLayer(
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/faisal/software/cling-build/cling-src/include/llvm/Support/Compiler.h:280:3: note: in definition of macro ‘LLVM_ATTRIBUTE_DEPRECATED’
   decl __attribute__((deprecated))
   ^~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-unused-local-typedef’
cc1plus: warning: unrecognized command line option ‘-Wno-covered-switch-default’
cc1plus: warning: unrecognized command line option ‘-Wno-nested-anon-types’
[100%] Building CXX object tools/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/ValueExtractionSynthesizer.cpp.o
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-unused-local-typedef’
cc1plus: warning: unrecognized command line option ‘-Wno-covered-switch-default’
cc1plus: warning: unrecognized command line option ‘-Wno-nested-anon-types’
[100%] Building CXX object tools/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/Value.cpp.o
[100%] Building CXX object tools/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/ValuePrinter.cpp.o
[100%] Building CXX object tools/cling/lib/Interpreter/CMakeFiles/obj.clingInterpreter.dir/ValuePrinterSynthesizer.cpp.o
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-unused-local-typedef’
cc1plus: warning: unrecognized command line option ‘-Wno-covered-switch-default’
cc1plus: warning: unrecognized command line option ‘-Wno-nested-anon-types’
[100%] Built target obj.clingInterpreter
Scanning dependencies of target clingInterpreter
[100%] Linking CXX static library ../../../../lib/libclingInterpreter.a
[100%] Built target clingInterpreter
Scanning dependencies of target cling
[100%] Building CXX object tools/cling/tools/driver/CMakeFiles/cling.dir/cling.cpp.o
[100%] Linking CXX executable ../../../../bin/cling
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
make[3]: *** [tools/cling/tools/driver/CMakeFiles/cling.dir/build.make:271: bin/cling] Error 1
make[3]: *** Deleting file 'bin/cling'
make[2]: *** [CMakeFiles/Makefile2:56050: tools/cling/tools/driver/CMakeFiles/cling.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:56062: tools/cling/tools/driver/CMakeFiles/cling.dir/rule] Error 2
make: *** [Makefile:12523: cling] Error 2
subprocess.CalledProcessError: Command 'make -j4 cling' returned non-zero exit status 2

┌──────────────────────────────────────────────────────────────────────────────┐
│ Clean up                                                                     │
└──────────────────────────────────────────────────────────────────────────────┘
Skipping build directory: /home/faisal/software/cling-build/builddir
Remove directory: /tmp/cling-obj/
`

**Comment by schnapper79** [comment]
`collect2: fatal error: ld terminated with signal 9 [Killed]`

This seems to be a "out of memory" - problem. For me it helped to make a big enough swapfile to add some.

**Comment by ferdymercury** [comment]
Could you retry with latest master and reopen if still an issue?
