### ISSUE TITLE
Doesn't compile on Fedora 34 with GCC 11.1.1

### ISSUE THREAD

**Issue by gromnitsky** [root-project/cling#413]
An excerpt from 'Porting to GCC 11':

> 'The following headers are used less widely in libstdc++ and may need to be included explicitly when compiled with GCC 11:
>
> * <limits> (for std::numeric_limits)'

So, after running `tools/packaging/cpt.py --create-dev-env Release --with-workdir=./_out --no-test` it failed on compiling `_out/cling-src/tools/llvm-exegesis/lib/Analysis.cpp` file.

I had to add `#include <limits>` to `_out/cling-src/utils/benchmark/src/check.h` & comment out a corresponding `fetch_llvm(llvm_revision)` line in `tools/packaging/cpt.py` before running `tools/packaging/cpt.py ...` again (otherwise it would undo my changes in the 'cling-src' repo).

**Comment by Axel-Naumann** [comment]
@reikdas @vgvassilev I can reproduce this. What do we do, add backport the relevant llvm patch? @reikdas can you help?

**Comment by ferdymercury** [comment]
Could you retry with latest master? I think it was solved here https://github.com/root-project/root/blame/master/interpreter/llvm-project/llvm/tools/llvm-exegesis/lib/Analysis.cpp
Reopen if it still fails, thanks
