### ISSUE TITLE
Is it possible to use Cling to load a higher version of "clang" (IE 11/12) than it was compiled with?

### ISSUE THREAD

**Issue by GavinRay97** [root-project/cling#420]
I spent some hours earlier attempting to get Clang + LibTooling from LLVM 12 working in a Jupyter notebook with Cling (the one provided by https://github.com/jupyter-xeus/xeus-cling).

But I didn't seem to be able to load another, newer version of Clang on top of what was being used to run the interpreter -- which is reasonable.

I'm curious if there a way to do a scoped "undefine" inside of an interpreted closure/statement so that I can say `'Hey, drop the definition and libs you currently have in-memory, and instead please use this other library'`?

The usecase being that developing Clang-based tools that work on C/C++ code in an interactive and visualizable way would be game-changing. My personal interest is codegen/bindings to other languages.

> _Imagine trying to work with/transform an AST, and you can see the tree and generated-code text stream visualized right in front of you. Brilliant!_

If it's not possible it's no big deal, I suppose could limit the use of Clang/LLVM libraries to version 9, but was just curious.

Thank you folks for an amazing tool! 🙏 

- Trying to run Recursive Visitor example as-is. Jupyter environment running on/compiled with `cling` v0.8 + `clang` 5:
	- ![image](https://user-images.githubusercontent.com/26604994/120726665-a19d7c00-c4a6-11eb-8163-06a86f1baaf7.png)

- Trying to include LLVM 13 and load `libclang-cpp.so`, results in a different set of errors (plus, it uses the old clang headers still):
	- ![image](https://user-images.githubusercontent.com/26604994/120726533-479cb680-c4a6-11eb-9229-d449176d34bb.png)

**Comment by pcanal** [comment]
> Is it possible to use Cling to load a higher version of "clang"

The short answer is no.  Upgrading Cling to be able to use newer version of Clang usually requires some adaptation and the next version will have the challenge that the jit used needs to be upgraded (i.e. a delicate part).

**Comment by SimeonEhrig** [comment]
> > Is it possible to use Cling to load a higher version of "clang"
> 
> The short answer is no. Upgrading Cling to be able to use newer version of Clang usually requires some adaptation and the next version will have the challenge that the jit used needs to be upgraded (i.e. a delicate part).

I think, you misunderstand the question. I think @GavinRay97 don't want to build Cling with a new version of Clang/LLVM. He wants to use a new version of libclang in Cling (e.g. `.L libclang-13.so`) and this does not work. I think, there is a name clash between both library version (the internal of Cling (LLVM 9) and the version on runtime (LLVM 13), because the libclang of Cling is not isolated in a own namespace. @Axel-Naumann Can you confirm this?

**Comment by GavinRay97** [comment]
@Axel-Naumann Thank you, that's exactly what I was curious about!

Is there something special/different about this `interpreter` sub-project in `ROOT` versus the `cling` repo here?
Wondering how easiest to set up a build that uses this config + integrate it with the Cling Jupyter kernel.

**Comment by Axel-Naumann** [comment]
Well, we configure things with the above CMakeLists.txt - that's all there is to it :-) Glad this was useful for you!
