### ISSUE TITLE
Building error - "default initialization of an object of const type without a user-provided default constructor"

### ISSUE THREAD

**Issue by pd3v** [root-project/cling#424]
### Describe the bug
Building cling by running `./cpt.py --create-dev-env Debug --with-workdir=./cling-build/` and at 97% building, 2 **default initialization of an object of const type without a user-provided default constructor** errors occur.

![cling 0 5 build errors](https://user-images.githubusercontent.com/3267138/129895462-b03f3044-e976-4261-8294-e90eae1e152b.png)

### Expected behavior
To build cling.

### To Reproduce
Run `./cpt.py --create-dev-env Debug --with-workdir=./cling-build/`

### Setup
1. I've tried with Cling 0.5 and Cling 0.8
2. MacOS 10.11.6
3. MacPorts

**Comment by Axel-Naumann** [comment]
Which compiler is this? Seems like a very strange error - something we've never seen before, on any platform...

**Comment by pd3v** [comment]
Confirmed. Thank you.

**Comment by Axel-Naumann** [comment]
OK thanks - we won't be fixing this then, please consider upgrading your macOS installation / compiler.
