### ISSUE TITLE
'cmakeDir' is not defined

### ISSUE THREAD

**Issue by indrakumarreddy007** [root-project/cling#426]
while Compiling Cpt.py in windows, I am getting the following error.

File "cpt.py", line 2308, im <module>
   get_win_dep()
File "cpt.py", line 1347, in get_win_dep
 os.rename(os.path.join(tmp_bin_dir, 'cmake-3.6.2-win64-x64'), cmakeDir)
NameERROR: name 'cmakeDir' is not defined

cmakeDir is not declared in cpt.py

when i tried to build using cmaketext.txt, i am facing 

CMake Error at CMakeLists.txt:42 (message):
  llvm-config not found -- LLVM_CONFIG-NOTFOUND

Could you please help to build cling project.
![ClingError](https://user-images.githubusercontent.com/37694439/130565553-3003f8b9-a45a-4986-a2bb-b3c49282c2c1.PNG)

**Comment by poopsicles** [comment]
editing the python script to add cmakeDir = TMP_PREFIX + "\bin\cmake\" worked for me
