### ISSUE TITLE
Instructions on https://root.cern/cling/cling_build_instructions/ are wrong

### ISSUE THREAD

**Issue by kasajian** [root-project/cling#431]
**It says:**
Alternatively, you can build manually. Start by checking out llvm, clang and cling:
```git clone http://root.cern/git/llvm.git src
cd src
git checkout cling-patches
cd tools
git clone http://root.cern/git/cling.git
git clone http://root.cern/git/clang.git
cd clang
git checkout cling-patches
cd ../..
```

Then use CMake to configure & build cling:

```
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=[Install Path] -DCMAKE_BUILD_TYPE=[Build configuration, e.g. Release or Debug] ..\src
cmake --build .
cmake --build . --target install
```

**Why this is wrong:**
Initially you cd into the src folder, then to the tools folder, then to clang.  So before the last step of the first section, you're in ./src/tools/clang, relative to where you started.   This means the next instruction, namely `cd ../..` will put you at src.
Now, in the next section it says to do, `mkdir build`, followed by `cd build`.  This means you're now in ./src/build.  But the first `cmake` refers to folder ..\src, which would refer to ./src/src, and this folder doesn't exist.   For ..\src path to be valid, the build folder needs to be a sibling of src.  I suspect the problem is that the step where it says `cd ../..` should be `cd ../../..`

Also, why is it `..\src` with a backlash, but in other sections it's a forward slash?

**Comment by ferdymercury** [comment]
Could you retry with https://root.cern/cling/cling_build_instructions/ and reopen if it still fails? Thanks
