### ISSUE TITLE
Link to Cling Webpage in README.md doesn't work

### ISSUE THREAD

**Issue by jonesmz** [root-project/cling#436]
E.g. https://cdn.rawgit.com/root-project/cling/master/www/index.html points to a file that is not rendered by the webbrowser.

**Comment by Axel-Naumann** [comment]
Thanks for your report, fixed in https://github.com/root-project/cling/commit/d59d27ad61f2f3a78cd46e652cd9fb8adb893565 (and the subsequent one, but details)
