### ISSUE TITLE
Building in Docker takes up too much space

### ISSUE THREAD

**Issue by michaelbrucelin** [root-project/cling#446]
### Building in docker takes up too much space

I built cling into a docker image, but the docker image is too big. Check the cling layer occupies 47.5GB. Is there any operation like clearing the cache, or reducing the database, etc., can make cling layer mirroring reduce some volume?

```bash
docker history michael/jupyterlab:latest
... ...
e36077b2262c   About an hour ago   /bin/sh -c jupyter-kernelspec install cling-…   157B      
98505b5edb56   About an hour ago   /bin/sh -c jupyter-kernelspec install cling-…   157B      
0a4417494a68   About an hour ago   /bin/sh -c jupyter-kernelspec install cling-…   158B      
29b200bf3dc9   About an hour ago   /bin/sh -c jupyter-kernelspec install cling-…   157B      
0eb1afc8015a   About an hour ago   /bin/sh -c python3 -m pip install -e .          1.42kB    
b6971615b90d   About an hour ago   /bin/sh -c #(nop) WORKDIR /usr/local/cling-b…   0B        
d2700f0e6394   About an hour ago   /bin/sh -c #(nop)  ENV PATH=/usr/local/cling…   0B        
0b4629cc781d   About an hour ago   /bin/sh -c ./cpt.py --check-requirements && …   47.5GB    
5f4e5d2ac39e   7 hours ago         /bin/sh -c chmod +x cpt.py                      96.5kB    
2a74ccf7ff43   7 hours ago         /bin/sh -c wget https://raw.githubuserconten…   96.7kB    
ea0058446ebd   7 hours ago         /bin/sh -c #(nop) WORKDIR /usr/local            0B        
... ...
```

Is there a way to reduce the size of the docker image? 47.5GB is a bit big, thank you very much.

**Comment by SimeonEhrig** [comment]
Did you configured the right build type? 47,5 GB looks like a debug build.

**Comment by michaelbrucelin** [comment]
> Did you configured the right build type? 47,5 GB looks like a debug build.

I only refer to the README file of this project, this is the content of my Dockerfile.

```
FROM debian:10
LABEL maintainer="michaelbrucelin@gmail.com"

WORKDIR /root

RUN apt-get update -y
RUN apt-get install -y sudo vim wget curl gcc cmake git

# python3
RUN apt-get install -y python3 python3-dev python3-pip
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install ipython jupyter jupyterlab ipywidgets qtconsole
RUN python3 -m pip cache purge

# C++
WORKDIR /usr/local
RUN wget https://raw.githubusercontent.com/root-project/cling/master/tools/packaging/cpt.py
RUN chmod +x cpt.py
# auto answer yes
RUN /bin/bash -c '/bin/echo -e "yes" | ./cpt.py --check-requirements && ./cpt.py --create-dev-env Debug --with-workdir=./cling-build/'; exit 0
# install cling kernel
ENV PATH="${PATH}:/usr/local/cling-build/builddir/bin"
WORKDIR /usr/local/cling-build/cling-src/tools/cling/tools/Jupyter/kernel
RUN python3 -m pip install -e .
RUN jupyter-kernelspec install cling-cpp17
RUN jupyter-kernelspec install cling-cpp1z
RUN jupyter-kernelspec install cling-cpp14
RUN jupyter-kernelspec install cling-cpp11
WORKDIR /root
```

**Comment by SimeonEhrig** [comment]
I'm not really familiar with `cpt.py`, but this line of code looks like, that it builds a debug build:

`RUN /bin/bash -c '/bin/echo -e "yes" | ./cpt.py --check-requirements && ./cpt.py --create-dev-env Debug --with-workdir=./cling-build/'; exit 0`

**Comment by SimeonEhrig** [comment]
If found this in the source code of `cpt.py`: https://github.com/root-project/cling/blob/f84e601d3f5cfd06f4b557780ca62e68d2cfa473/tools/packaging/cpt.py#L1803

Can you try to change the value of the parameter `--create-dev-env` to `Release` and build the container again?

**Comment by michaelbrucelin** [comment]
Okay, I will try it again, thank you very very much.

**Comment by michaelbrucelin** [comment]
> If found this in the source code of `cpt.py`:
> 
> https://github.com/root-project/cling/blob/f84e601d3f5cfd06f4b557780ca62e68d2cfa473/tools/packaging/cpt.py#L1803
> 
> Can you try to change the value of the parameter `--create-dev-env` to `Release` and build the container again?

I've been busy recently, and I haven't had time to test it. I just tested it and it has dropped to 1.77GB. The effect is very obvious. Thank you so much.

```
a273938157ef   About an hour ago   /bin/sh -c /bin/bash -c '/bin/echo -e "yes" …   1.77GB
```
