### ISSUE TITLE
CPT build faile

### ISSUE THREAD

**Issue by ldotrg** [root-project/cling#448]
- [ ] Checked for duplicates

### Describe the bug

20:54:03  /cling-build/cling-src/tools/cling/lib/Interpreter/DynamicLibraryManagerSymbol.cpp:621:43: error: ‘DF_1_PIE’ is not a member of ‘llvm::ELF’
20:54:03             if (Dyn.d_un.d_val & llvm::ELF::DF_1_PIE)
20:54:03                                             ^~~~~~~~
20:54:03  /cling-build/cling-src/tools/cling/lib/Interpreter/DynamicLibraryManagerSymbol.cpp:621:43: note: suggested alternative: ‘DF_1_NOW’
20:54:03             if (Dyn.d_un.d_val & llvm::ELF::DF_1_PIE)
20:54:03                                             ^~~~~~~~
20:54:03                                             DF_1_NOW

```
python3 /cpt.py --create-dev-env Release --with-workdir=./cling-build/ --no-test
```

### Expected behavior
Should build pass

### Setup

wget https://raw.githubusercontent.com/root-project/cling/master/tools/packaging/cpt.py
chmod +x /cpt.py
python3 /cpt.py --create-dev-env Release --with-workdir=./cling-build/ --no-test

**Comment by SimeonEhrig** [comment]
@vgvassilev I also recognized this bug, yesterday. I think, the reason is a missing back port of a llvm 11 feature in the CERN llvm fork.

The bug was introduced by this commit: https://github.com/root-project/cling/commit/4fa39ba82f55cf8975ba635c71c964249219b7a6

**Comment by Axel-Naumann** [comment]
Should be fixed! Can you confirm?

**Comment by SimeonEhrig** [comment]
The normal cmake build is working. I expect `cpt` is also working again.

**Comment by 7r3nzy** [comment]
I am getting the same error:

Downloaded the script file from [here](https://raw.githubusercontent.com/root-project/cling/master/tools/packaging/cpt.py)
