### ISSUE TITLE
Creating thread_local object with user-defined destructor causes segfault

### ISSUE THREAD

**Issue by dimitry-ishenko** [root-project/cling#465]
- [x] Checked for duplicates

### Describe the bug

A picture is worth a thousand words:
![segfault](https://user-images.githubusercontent.com/2858291/185190563-fac7b576-6a4b-46b9-bba5-1e847d376668.gif)

### Expected behavior

Not having a segfault would be nice.

### To Reproduce

1. Open cling
2. Enter
   ```c++
   struct st { ~st() { } };
   thread_local st s;
   ```
3. Exit cling
4. Observe cling barf with segfault

### Setup

cling 0.9
Ubuntu 22.04 LTS

**Comment by dimitry-ishenko** [comment]
Please not that `~st` doesn't actually get called. In other words, if we modify the above example to this:
```bash
dimitry@laptop:~$ cling

****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
[cling]$ #include <iostream>
[cling]$ struct st { ~st() { std::cout << "~st\n"; } };
[cling]$ thread_local st s;
[cling]$ .q
Segmentation fault
dimitry@laptop:~$
```
Please notice that nothing gets printed in the terminal.

However, if I exit via `std::exit()` then the destructor **is** called:
```bash
dimitry@laptop:~$ cling

****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
[cling]$ #include <iostream>
[cling]$ struct st { ~st() { std::cout << "~st\n"; } };
[cling]$ thread_local st s;
[cling]$ exit(1)
~st
dimitry@laptop:~$ 
```

**Comment by dimitry-ishenko** [comment]
Does anybody read or care about these issues?

**Comment by bellenot** [comment]
Sorry for the long delay, maybe @vgvassilev or @Axel-Naumann can take a look?

**Comment by vgvassilev** [comment]
> Does anybody read or care about these issues?

Yes, we do. However, we have been spending most of our time to upgrade cling to use llvm13. There most of these issues are solved by the new orcv2 jit infrastructure. I would expect to work on this bug if one can reproduce it with llvm13.

**Comment by dimitry-ishenko** [comment]
@bellenot @vgvassilev thanks guys. I get it now. @vgvassilev is the llvm13 branch available anywhere?

**Comment by Axel-Naumann** [comment]
It's here: https://github.com/vgvassilev/root/tree/llvm13

**Comment by vgvassilev** [comment]
You can pick it up also from vgvassilev/cling where I have the llvm and clang forks with the same llvm13 branches synced

**Comment by dimitry-ishenko** [comment]
Thanks guys and sorry for high-jacking the issue. One more question for @vgvassilev: the branch I am looking for in your cling, llvm and clang projects is `cling-patches-llvm13`, correct?

**Comment by vgvassilev** [comment]
Correct

**Comment by dimitry-ishenko** [comment]
@vgvassilev FWIW it's still happening with the version of cling from your repo (https://github.com/vgvassilev/cling/tree/cling-patches-llvm13):

```bash
root@laptop:~# /usr/local/bin/cling --version
1.0~dev
root@laptop:~# /usr/local/bin/cling -std=c++20

****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
[cling]$ struct st { ~st() { } };
[cling]$ thread_local st s;
[cling]$ .q
Segmentation fault
root@laptop:~# 
```
I see there are some additional patches in the ROOT version of cling (https://github.com/vgvassilev/root/tree/llvm13/interpreter/cling). Should I go ahead and try to cherry-pick them out of that repo?

**Comment by ferdymercury** [comment]
I tried with the latest master (LLVM16 upgrade) and it seems that it no longer segfaults.

```
#include <iostream>
struct st { ~st() { std::cout << "~st\n"; } };
thread_local st s;
.q
~st
```

Can you try on your side?
