### ISSUE TITLE
An API to display the search directories (include and libraries) used by cling at runtime.

### ISSUE THREAD

**Issue by SylvainCorlay** [root-project/cling#473]
Is there a means to display the currently used include directories and other search directories?

(This is coming up in the context on some issue with respect to sysroot detection on OSX)

**Comment by SimeonEhrig** [comment]
Yes, you can get the include paths via the `gCling` object (type: `cling::Interpreter`).

```c++
****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************

[cling]$ #include "cling/Interpreter/Interpreter.h"
[cling]$ #include <string>
[cling]$ #include "llvm/ADT/SmallVector.h"
[cling]$ // 20 is the vector size
[cling]$ llvm::SmallVector<std::string, 20> incPaths;
[cling]$ gCling->GetIncludePaths(incPaths, true, true);
[cling]$ incPaths
```

Here is the [link](https://github.com/root-project/cling/blob/a3805bb26d8bd8284c1278d3d55d265bc2048f2a/include/cling/Interpreter/Interpreter.h#L458) to the function declaration of `GetIncludePaths`.

**Comment by SylvainCorlay** [comment]
Thanks!
