### ISSUE TITLE
scanf does not work in cling

### ISSUE THREAD

**Issue by pankajkumar229** [root-project/cling#474]
- [x] Checked for duplicates

### Describe the bug
scanf does not work in cling, only cin does.

### Expected behavior
scanf should issue a prompt like cin does

### To Reproduce
#include <stdio.h>
int n;
scanf("%d", &n);

**Comment by edfink234** [comment]
Uh, works for me (in 6.26/10, macosxarm64)

```C++
root [0] int n; scanf("%d", &n);
5
root [1] n
(int) 5
```

**Comment by ferdymercury** [comment]
Seems to work with current master, too.
