### ISSUE TITLE
init config

### ISSUE THREAD

**Issue by Freed-Wu** [root-project/cling#498]
Can cling have a init config like `~/.config/cling/init.c`:

```c
#include <stdlib.h>
```

Then every time user enter `cling` will include `<stdlib.h>` automatically, don't need to input the same code every time.

About `~/.config/cling`, See [XDG](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Comment by Axel-Naumann** [comment]
We now have `.cling-init` support, see https://github.com/root-project/root/pull/11262#issuecomment-1256155643
