### ISSUE TITLE
Build fails: Could not open file for write in copy operation /usr/local/llvm15/lib/cmake/cling/ClingConfig.cmake.tmp

### ISSUE THREAD

**Issue by yurivict** [root-project/cling#499]
### Describe the bug
cmake configure attempts to write a file into a read-only location under $PREFIX.

```
-- And then fallback to: 'ccache'
CMake Error: Could not open file for write in copy operation /usr/local/llvm15/lib/cmake/cling/ClingConfig.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at cmake/modules/CMakeLists.txt:22 (configure_file):
  configure_file Problem configuring file
```

### Setup
1. Cling version: rev.6d52a95
2. Operating system: FreeBSD 13.1
3. How you obtained Cling, such as with cpt.py: GitHub

**Comment by Axel-Naumann** [comment]
/usr/local/llvm15 won't work, you need to use llvm-project from https://github.com/root-project/llvm-project - use the branch called `cling-llvm13`. Does that help?
