### ISSUE TITLE
Build failure with GCC 13

### ISSUE THREAD

**Issue by lahwaacz** [root-project/cling#506]
Building cling from the master branch with GCC 13 gives me these errors:

```
/build/cling-git/src/llvm/include/llvm/Support/Signals.h:119:8: error: variable or field ‘CleanupOnSignal’ declared void
  119 |   void CleanupOnSignal(uintptr_t Context);
      |        ^~~~~~~~~~~~~~~
/build/cling-git/src/llvm/include/llvm/Support/Signals.h:119:24: error: ‘uintptr_t’ was not declared in this scope
  119 |   void CleanupOnSignal(uintptr_t Context);
      |                        ^~~~~~~~~
/build/cling-git/src/llvm/include/llvm/Support/Signals.h:18:1: note: ‘uintptr_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   17 | #include <string>
  +++ |+#include <cstdint>
   18 |
```

**Comment by Axel-Naumann** [comment]
[In our branch](https://github.com/root-project/llvm-project/blob/cling-llvm13/llvm/include/llvm/Support/Signals.h#L17) that include exists. You're likely not using the right llvm. Where does yours come from?

**Comment by lahwaacz** [comment]
Hmm, I'm building [cling-git](https://aur.archlinux.org/packages/cling-git) from the AUR, which tracks http://root.cern.ch/git/llvm.git (branch `cling-patches`). Is it not a mirror of this repo?

**Comment by Axel-Naumann** [comment]
No, we moved. I will disable the repos on root.cern to make this more obvious. Probably won't happen before August.

**Comment by lahwaacz** [comment]
Oh, I see. Thanks for the explanation.
