### ISSUE TITLE
Evaluate Profile-Guided Optimization (PGO)

### ISSUE THREAD

**Issue by zamazan4ik** [root-project/cling#508]
Hi!

Recently I checked Profile-Guided Optimization (PGO) improvements on multiple projects. The results are [here](https://github.com/zamazan4ik/awesome-pgo/). LLVM-related results are [here](https://github.com/llvm/llvm-project/issues/63486).

Since PGO showed measurable improvements in compiler-like loads (Clang, Clangd, clang-format, GCC, Rustc, etc.) I think it could be useful to check PGO on Cling as well.

We need to perform PGO benchmarks on Cling. And if it shows improvements - add a note about possible improvements Cling performance with PGO. Providing an easier way (e.g. a build option) to build scripts with PGO can be useful for the end-users too.

**Comment by pavel-the-best** [comment]
I think this is certainly a reasonable way to improve Cling's performance.

**Comment by ferdymercury** [comment]
Referred to https://github.com/root-project/root/issues/15778
