### ISSUE TITLE
about latest tag release

### ISSUE THREAD

**Issue by sequoiar** [root-project/cling#512]
### Is your feature request related to a problem? Please describe.
Is there any plan to tag release from latest master branch ?

### Describe the solution you'd like
tag release from latest master branch

### Describe alternatives you've considered
NA

### Additional context
NA

**Comment by ferdymercury** [comment]
See https://github.com/root-project/cling/releases/tag/v1.0 and https://root-forum.cern.ch/t/cling-1-1-release-plans/58991
