### ISSUE TITLE
CUDA __global__ function definition fails

### ISSUE THREAD

**Issue by gnrv** [root-project/cling#513]
- [X] Checked for duplicates

### Describe the bug
I tried to perform the steps in https://blog.llvm.org/posts/2020-12-21-interactive-cpp-for-data-science, the CUDA section by @SimeonEhrig 

All I got on Ubuntu WSL2 and Windows 11 (Visual Studio Community 2022) was (using Windows as example here)

```
arvid@gnrv-x1-carbon MSYS ~/GitHub/cling-build
$ /c/Program\ Files\ \(x86\)/LLVM/bin/cling.exe

****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
[cling]$ #pragma cling(load "cublas64_11.dll")
[cling]$ #pragma cling add_include_path("C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\include")
[cling]$ #include <cublas_v2.h>
[cling]$ __global__ void init(float *matrix, int size){
[cling]$ ?   }
input_line_8:2:47: error: function definition is not allowed here
 __global__ void init(float *matrix, int size){
                                              ^
```

Similar on WSL2:
```
anilsson@gnrv-x1-carbon:~$ cling

****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
[cling]$ #include <iostream>
[cling]$ .I /usr/local/cuda/include
[cling]$ #include <cublas_v2.h>
[cling]$ #pragma cling(load "libcublas.so")
[cling]$ __global__ void init(float *matrix, int size){
[cling]$ ?   int x = blockIdx.x * blockDim.x + threadIdx.x;
[cling]$ ?   if (x < size)
[cling]$ ?   matrix[x] = x;
[cling]$ ?   }
input_line_6:2:47: error: function definition is not allowed here
 __global__ void init(float *matrix, int size){
                                              ^
```

### Expected behavior
Be able to declare a CUDA kernel

### To Reproduce
Build latest master with the llvm-13 branch of llvm-project

### Setup
Built Cling using updated instructions on root-project / web

**Comment by SimeonEhrig** [comment]
Hey, @gnrv 

You need to run `cling -x cuda` to enable the CUDA mode. This does also automatically include the cuda header and links the cuda runtime library. I believe, for cublas you need still to include exta header and link extra libraries. But with `cling -x cuda` you should be able to define a CUDA kernel and run it out of the box.

Cheers,
Simeon

**Comment by SimeonEhrig** [comment]
If think in the second example, Cling should detect CUDA SDK location correctly. For the first example, you need to set the CUDA SDK location manually: `LD_LIBRARY_PATH="C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\lib64" ./cling -xcuda --cuda-path="C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6"`

**Comment by gnrv** [comment]
Thank you very much for getting back to me so quickly =D I will check it tonight and close the issue!

**Comment by SimeonEhrig** [comment]
No problem. I'm pretty interested in the result. Native Windows should not work, because some code paths for Windows are missing but in WLS it could work. I saw other projects running on WLS on computers of colleges, where I never thought this could work.

**Comment by SimeonEhrig** [comment]
@gnrv That's impressive!
We know the problem of segmentation faults and there are already ideas and concepts how to recover it, e.g. that the Jit is executing the code in a child process, which is transparent for the user.
