### ISSUE TITLE
Homebrew formula for 1.0 | help needed

### ISSUE THREAD

**Issue by clashman** [root-project/cling#525]
I was just trying to add the new cling release to the homebrew package manage but was facing some problems.

https://github.com/Homebrew/homebrew-core/pull/171856

Mainly, for some reason clings build path is hardcoded as the default resource-dir, so that I have to pass that switch manually when cling is run. I spent way too much time trying to follow the code that leads to this. Maybe someone can help resolving this.

**Comment by ferdymercury** [comment]
Maybe @AndrewSB or @hahnjo have some ideas.

**Comment by AndrewSB** [comment]
honored i was mentioned. but no, i haven't used cling for a while
