### ISSUE TITLE
cpt.py cannot find required packages. Fedora25

### ISSUE THREAD

**Issue by furkanusta** [root-project/cling#79]
When I run ./cpt.py --check-requirements I get error

> subprocess.CalledProcessError: Command 'rpm -qa | grep -w ...' returned non-zero exit status 1

It prints the same thing for git, gcc, gcc-c++ and rpm-build even though they are all installed

However, when I run 'rpm -qa | grep ..' myself it finishes without a problem.

I didn't continue further, it is possible that even though requirement check fails, other parts might be working.

Edit: My python version is 2.7.12

**Comment by Axel-Naumann** [comment]
If @vgvassilev can't help then maybe you can try with one of the alternative build procedures described here https://root.cern/cling-build-instructions

**Comment by Axel-Naumann** [comment]
Please use https://root.cern/cling-build-instructions if cpt has problems.
